### ISSUE TITLE
Custom validator for built-in type

### ISSUE THREAD

**Issue by shhlkien** [icebob/fastest-validator#100]
How can I write a custom validate function for built-in type instead of rewriting entire object?
e.g:
```js
const validator = new Validator();

const schema = {
  email: {
    type: "email",
    // expect new custom validator
    custom: function() {
      // check for duplicate email in database
     return duplicate ? false : true; 
    }
  }
};

const validate = validator.compile(schema);

validate({ email: "example@mail.com" })
```

**Comment by mahovich** [comment]
Было бы удобно использовать Пользовательский валидатор таким образом

`const Validator = require("fastest-validator");

const v = new Validator();

const schema = {
  color: {
    type: "string",
    length: 7,
    optional: true,
    check(value) {
      return /^#[0-9a-fA-F]$/.test(value);
    }
  }
};

const validate = v.compile(schema);

console.log(validate({ color: "FAIL" }));
`
