### ISSUE TITLE
index.d.ts fix RuleCustom

### ISSUE THREAD

**Issue by ajaishankar** [icebob/fastest-validator#102]
Move the indexed field `[key: string]: any` from `RuleCustom` to `RuleCustomInline` 

https://github.com/icebob/fastest-validator/blob/master/index.d.ts#L448

This makes sure invalid properties cannot be added to say a RuleString.

`
let r: RuleString = { type: "string", foo: "bar" }
`

**Comment by erfanium** [comment]
@icebob I think this issue has been resolved
