### ISSUE TITLE
Feature request: Return keyed object instead of array?

### ISSUE THREAD

**Issue by ispyinternet** [icebob/fastest-validator#103]
Currently you return an array of errors and so if you want to pull out an error for a particular field you need to loop the array or post process it into a keyed object.

I'm wondering if there is any driving reason for the array and whether a keyed object would be a better return value?

**Comment by icebob** [comment]
You can't always put the errors in an object structure. E.g. you have an array with object which contains array again... or a circular object type....
So array is better. On the other hand, it would cause big breaking change.

**Comment by ispyinternet** [comment]
👍
