### ISSUE TITLE
Feature request: Currency rules

### ISSUE THREAD

**Issue by TriStarGod** [icebob/fastest-validator#110]
Hi,
Great library. I was wondering if you had a money / currency rule and if not, what do you use?

**Comment by ishan-srivastava** [comment]
@erfanium I just stumbled upon this awesome lib.
Mind if I take this issue?

**Comment by erfanium** [comment]
@ishan-srivastava Yes, You can start a pull request

**Comment by ishan-srivastava** [comment]
@erfanium I have added the PR, please have a look.
