### ISSUE TITLE
React hook form integration not working

### ISSUE THREAD

**Issue by cmnstmntmn** [icebob/fastest-validator#112]
hei,

i'm having the following:

```js
//validator.js
import Validator from "fastest-validator";

const schema = {
  Email: "string"
};

function validationSchema(ob) {
  let validator = new Validator();
  let check = validator.compile(schema);
  let result = check(ob);

  return result;
}

export default validationSchema;
```

and my component

```js
//component.js

const Form = () => {
  const { register, formState } = useForm({
    validationSchema: validationSchema,
    mode: "onInput"
  });

 return(
    <form>
       <input id="Email" name="Email" ref={register} />
    </form>
  )
}
```

for some reason, is not working and no errors are thrown

**Comment by Gamote** [comment]
@cmnstmntmn You have multiple things that set you far away from your desired outcome. From what I guessed, the `useForm` is coming from `react-hook-form` library. Now, if you read their documentation you will find the next sentence: **`React Hook Form currently supports Yup for object schema validation.`** ([source](https://react-hook-form.com/api/#validationSchema))

This being said, what are you trying to accomplish it's not possible using this library.

Recommendations:
- `useForm` will return an object that contains the `errors` property. Use it to debug your code.
- next time when you create an issue try to provide an [MVE](https://stackoverflow.com/help/minimal-reproducible-example) to maximise your chances to receive an answer.

@icebob Can you please close this issue?
