### ISSUE TITLE
How can allow field nulllabe?

### ISSUE THREAD

**Issue by vfa-tunq** [icebob/fastest-validator#113]
I have a problem, how can I allow a field nullable. Many thanks.
```js
const v = new Validator();

const schema: ValidationSchema = {
  name: { type: 'string', default: null}
};

console.log(v.validate({ name: null }, schema)); // I want to valid but I got error below. :(
```
```bash
[
  {
    type: 'required',
    message: "The 'name' field is required.",
    field: 'name',
    actual: null
  }
]
```

**Comment by Gamote** [comment]
@vfa-tunq You can use the `optional` property like this:

```js
const v = new Validator();

const schema = { name: { type: 'string', optional: true } };

v.validate({ name: null }, schema); // "true"
```

The problem with this is that you'll receive `true` as well if the `name` field is `undefined`. If you are looking for a way to require the field but allow it to be `null`, there's none at the moment.

**Comment by erfanium** [comment]
@JHawkley I have a generic idea, something like this:
```js
schema =  {
   foo: { 
      type: "string",
      allow: [null]
   },
}
```
So we can allow everything we want, not just `null`

**Comment by erfanium** [comment]
Another idea:
‍‍‍```js
schema = {
   foo: {
      type: "string"
      pre(value , skip){
         if (value === null) return skip(value)
         return value
      }
   }
}
```

**Comment by intech** [comment]
@erfanium I looked at the logic `equal` and I think that we could modify it so that not for all types to use the serialization `JSON.stringify()` and then not lose strict comparison for `null`.

**Comment by erfanium** [comment]
@intech When we can offer a more complete solution with a little change, why not?
I think `multi` rule is not a good idea for this little problem, This complicates the story, and it has a performance penalty (because it will execute two more rules)

**Comment by intech** [comment]
@erfanium You can add the rule, but so far I have not been able to come up with a single case of using this rule.
I agree with your arguments.

**Comment by erfanium** [comment]
@intech @JHawkley 
In my opinion, @JHawkley 's idea is more appropriate now, we can have `nullable` property along with `optional`

### Just `nullable`
```js
const schema = {
   foo: {
      type: "string",
      nullable: true
   }
}

check({}) // error
check({ foo: null }) // ok
```

###  `optional` with `nullable`
```js
const schema = {
   foo: {
      type: "string",
      nullable: true
   }
}

check({}) // ok
check({ foo: null }) // ok
```

**Comment by icebob** [comment]
@erfanium I like the `nullable` solution. It should be checked in the common "require/optional" code parts and maybe it will work in all rules.

**Comment by erfanium** [comment]
@icebob 
The problem with current logic is that you should always write this piece of code in `custom` function : `if (!value) return value`, Most of the time I forget this.

> And it doesn't cause breaking change.
We can release v2.0.0, I think we should do the right thing and not get involved in backward compatibility.
