### ISSUE TITLE
Introduce optional & empty into more types

### ISSUE THREAD

**Issue by simon-fraser** [icebob/fastest-validator#116]
I have found a few scenarios using various types where an optional or empty flag is needed.

For example the types "url" or "email" cannot be empty or optional
Neither can the type string when using a pattern.

**Comment by Gamote** [comment]
@simon-fraser Do you see any other types that needs the `empty` or `optional` property?

**Comment by simon-fraser** [comment]
Great start @Gamote, I cannot say that I uncovered any other types with this issue.

**Comment by Gamote** [comment]
@icebob #149, #150 and #151 PRs should solve this issue, can you close it?
