### ISSUE TITLE
Correct behavior of $$strict and $$root in nested object schema

### ISSUE THREAD

**Issue by FFKL** [icebob/fastest-validator#123]
Hello! Should `$$strict` and `$$root` works with `type: 'object'` in `props`?
```javascript
{
    example: {
      type: "object",
      props: {
        test: "string",
        $$strict: true // works in 0.6.19, but in 1.1.0 - Error: Invalid 'undefined' type in validator schema.
      }
    }
  }
```

**Comment by icebob** [comment]
As of 1.x.x the `$$strict` property is removed and a new `strict` rule property has been added to `object` rule. https://github.com/icebob/fastest-validator/blob/master/CHANGELOG.md#sanitizations

The `$$root` property can be used only on the root level object, not on nested objects.

**Comment by FFKL** [comment]
@icebob thanks, got it
