### ISSUE TITLE
Feature Request: Validate array ordered

### ISSUE THREAD

**Issue by simlu** [icebob/fastest-validator#124]
This is important when e.g. validating GPS coordinate tuples.

Could allow array to be passed for `items` parameter in array?

Please let me know what you think about this addition! Cheers!

**Comment by icebob** [comment]
yes, e.g.:
```js
{
    type: "array", items: {
        type: "array", items: {
            type: "number"
        }
    }
}
```

**Comment by simlu** [comment]
Hello icebob. This is not what I meant at all.

I'm trying to get validation for `[180, 90]` valid, but `[90, 180]` invalid.

**Comment by icebob** [comment]
I see. It is not available. You should do it with a custom validator only.

**Comment by simlu** [comment]
@icebob Would you be ok with extending the functionality with an additional flag on the array `exact=BOOL`? After reviewing this I think that's all that would be needed here

**Comment by icebob** [comment]
And what will be the logic behind `exact`? The `items` will be an array with schemas?

**Comment by simlu** [comment]
We can already provide an array for items. So it would just ensure
- array length matches items length
- the entries in array validate against corresponding items entries

Schema would look as follows:

```json
{
    type: "array", exact: true, items: [
      { type: "number", min: -180, max: 180 },
      { type: "number", min: -90, max: 90 }
    ]
}
```

**Comment by erfanium** [comment]
@simlu @simlu 
We can add a new type named: **Tuple**, like Typescript:
https://www.typescriptlang.org/docs/handbook/basic-types.html#tuple

**Comment by icebob** [comment]
A new rule type? Or inside `array` type?

**Comment by erfanium** [comment]
@icebob new rule. like
```
{
   foo: {
      type: 'tuple',
      0: 'string',
      1: {
             type: 'number',
             min: 10 
          }
   }
}
```

**Comment by icebob** [comment]
I like the second option, it follows the structure of other rules.

**Comment by erfanium** [comment]
@icebob 
Can you add `Good-first-issue` tag for this?

**Comment by Gamote** [comment]
@icebob I've created a PR for this #147

**Comment by Gamote** [comment]
@icebob #147 PR should solve this issue, can you close it?
