### ISSUE TITLE
Exit on first error

### ISSUE THREAD

**Issue by erfanium** [icebob/fastest-validator#134]
This option can greatly increase speed.

**Comment by icebob** [comment]
It's true, but sometimes it's useful to detect all errors. E.g. on a web form. Better to give all errors than one-by-one. So it can be implemented with a new constructor option.

**Comment by erfanium** [comment]
@icebob 
How do you think we can implement this?
I think by using `throw` keyword in `makeError` and a catch via `try catch`

**Comment by icebob** [comment]
The throw, try-catch is an expensive operation, I think it will cut down the performance. I'm going to check the source and think out how it can be implemented.

**Comment by icebob** [comment]
I've checked the code and I think we need to handle it only in `object` rule because it handles the root object as well.
We should place an exit code to here:
https://github.com/icebob/fastest-validator/blob/2893a0e69aa97129e75d21f9354b844641552daa/lib/rules/object.js#L57-L59

Like:
```js
if (this.opts.stopAtFirstError)
  sourceCode.push(`
	if (errors.length > 0)
		return parentObj;
`);
```
