### ISSUE TITLE
[FEATURE] oneOf flag for object properties

### ISSUE THREAD

**Issue by mihaispataru** [icebob/fastest-validator#138]
Hi,

i'm trying right now to handle a scenario to validate an object schema that has all the properties optional, but it is mandatory to have at least one property available for the schema to be valid.

Example:

```javascript
const schema = {
  example: {
    type: 'object',
    oneOf: true, // future flag, not implemented right now
    props: {
      prop1: { type: 'string', optional: true },
      prop2: { type: 'string', optional: true },
    },
  }
};
```

I can help with the development if you think that this can be a feature that you to implement. Right now i'm developing this as a custom validator.

**Comment by icebob** [comment]
Hi,

PR would be great.

**Comment by erfanium** [comment]
@icebob 
what about `$or` operator?:

```js
schema = {
   $or: [
      { type: "object", props: { foo: "string" } },
      { type: "object", props: { foo2: "string" } }
   ]
}
```

**Comment by icebob** [comment]
It can be good but I have no idea how it can be implemented without adding too much complexity to the code.

**Comment by erfanium** [comment]
@icebob 
I totally forgot about current `Multi` rule.
I think It's now possible with it.

**Comment by icebob** [comment]
Ohhh, really. I've also forgotten it. @mihaispataru it covers your use-case?

**Comment by erfanium** [comment]
@icebob I think using atomic-operations like `$or` , `$and` are more understandable for users than crating new rules for this. It's Simple to implement, I'm working on it

**Comment by icebob** [comment]
What is the use-case for `$and`?

**Comment by erfanium** [comment]
@icebob Not normally, but it can have.
for example: validating a numbering string that should between 0 and 100

```js
const schema = {
   foo: {
      $and: [
         { type: "string", numeric: true, convert: true  },
         { type: "number", min: 0, max: 100 }
      ]
   }
}
```

**Comment by mihaispataru** [comment]
> Ohhh, really. I've also forgotten it. @mihaispataru it covers your use-case?



> @icebob
> I totally forgot about current `Multi` rule.
> I think It's now possible with it.
> 
> ```js
> const schema = {
>     status: { type: "multi", rules: [
>        { type: "object", props: { foo: "string" } },
>        { type: "object", props: { foo2: "string" } }
>     ]}
> }
> ```

I've already tried this approach, but it doesn't cover the scenario, because if the we have an empty "status" object the validation will pass. I need the possibility to "force" one of the optional rules. So i need a why to enforce the use of one of "foo" or "foo2" property.

**Comment by mihaispataru** [comment]
> @icebob Not normally, but it can have.
> for example: validating a numbering string that should between 0 and 100
> 
> ```js
> const schema = {
>    foo: {
>       $and: [
>          { type: "string", numeric: true, convert: true  },
>          { type: "number", min: 0, max: 100 }
>       ]
>    }
> }
> ```
> 
> `$or` is more usable

Yes, this approach sounds more suitable. I was actually thinking of the "multi" type with a flag of "$or" or "$and", like the way they handle it in MongoDB queries.

```
const schema = {
    status: { type: "multi", $or: true, rules: [
       { type: "object", props: { foo: "string" } },
       { type: "object", props: { foo2: "string" } }
    ]}
}
```

Or the same flag only for the "object" type.

Unfortunately i haven't had enough time to look over the source code to see which of the features implies less development time.

**Comment by erfanium** [comment]
> > Ohhh, really. I've also forgotten it. @mihaispataru it covers your use-case?
> 
> > @icebob
> > I totally forgot about current `Multi` rule.
> > I think It's now possible with it.
> > ```js
> > const schema = {
> >     status: { type: "multi", rules: [
> >        { type: "object", props: { foo: "string" } },
> >        { type: "object", props: { foo2: "string" } }
> >     ]}
> > }
> > ```
> 
> I've already tried this approach, but it doesn't cover the scenario, because if the we have an empty "status" object the validation will pass. I need the possibility to "force" one of the optional rules. So i need a why to enforce the use of one of "foo" or "foo2" property.

It works, no doubt.
Look at this example:

```js
const check = v.compile({
	$$root: true,
	type: "multi", 
	rules: [
		{type: "object" , props: { r: "string", a: "string" }},
		{type: "object" , props: { r: "string", b: "string" }},
	]
});

console.log(check({r: "s", a: "s"}));  // true
console.log(check({r: "s", b: "s"}));   // true
console.log(check({a: "s"}));  // error
console.log(check({}));  // error
```
