### ISSUE TITLE
Default value for schema  properties

### ISSUE THREAD

**Issue by prieston** [icebob/fastest-validator#14]
Can someone add default values to schema properties ? eg
    {
        email: { type: 'emai', default: 'test@test.com' }
    }

**Comment by alexeymarunin** [comment]
Any progress?

**Comment by akazakou** [comment]
I guess it will not be implemented till #44 sanitizers functionality will be available.

**Comment by omarsafwany** [comment]
Any updates?!

**Comment by icebob** [comment]
https://github.com/icebob/fastest-validator/pull/94
