### ISSUE TITLE
Custom inline validator not executing | Source data not available in custom validator

### ISSUE THREAD

**Issue by ThisIsRuddy** [icebob/fastest-validator#141]
Hi,

I have output all the available parameters when defining a custom validator but I can't find access to the source data anywhere which is preventing me from creating cross-field validations.

Please tell me I'm just blind from staring at data all-day 😂

Below is a basic example coded up but the 'custom' validator does not execute and even if it did I do not see any source data parameters being passed in:
[https://pastebin.com/WyzSeVXV](https://pastebin.com/WyzSeVXV)

**Comment by icebob** [comment]
Please create a repro example on [repl.it](https://repl.it/@icebob/custom-validator)

**Comment by ThisIsRuddy** [comment]
I expect there to be something logged to the console from the custom function on the schema but nothing happens? Thanks again in advance

[https://repl.it/repls/RobustSwelteringDevelopments](https://repl.it/repls/RobustSwelteringDevelopments)

**Comment by icebob** [comment]
It won't work because the `alternateAddress` is not in the target object and it's optional, so the custom check is not called.

**Comment by icebob** [comment]
You should move this custom function into the root and check the `deliverToAlternativeAddress` flag.
E.g: it can work: https://repl.it/join/zcujtgmt-icebob

**Comment by erfanium** [comment]
@icebob We can implement  `$$custom` for root.
E.g:
```js
v.compile({
   foo: "string",
   bar: "number",
   $$custom() {
     //...
   }
})
```

**Comment by ThisIsRuddy** [comment]
You have solved my issues thank you! 

@erfanium could you elaborate a little please? :)

**Comment by erfanium** [comment]
@ThisIsRuddy I was discussing about a new feature that simplifies using `customValidator` for root object.
