### ISSUE TITLE
deno support has issue

### ISSUE THREAD

**Issue by davidxiao** [icebob/fastest-validator#144]
deno version: 1.0.2

can not bundle as below

Pro-2:libs$ cat fast-validator.ts 
import FastestValidator from "https://dev.jspm.io/fastest-validator";

const v = new FastestValidator();
const check = v.compile({
        name: "string",
        age: "number",
});

console.log(check({ name: "Erf", age: 18 }));
console.log(check({ name: "Erf" }));
console.log(check({ name: "Erf", age: "18" }));

Pro-2:libs$ deno bundle ./fast-validator.ts aa.js
Bundling file:.../libs/fast-validator.ts
error: TS2351 [ERROR]: This expression is not constructable.
  Type '{}' has no construct signatures.
const v = new FastestValidator();
              ~~~~~~~~~~~~~~~~
    at file:..../libs/fast-validator.ts:3:15

**Comment by davidxiao** [comment]
but pika version works:
`import pkg from "https://cdn.pika.dev/fastest-validator@^1.4.1";

const v = new pkg();
const check = v.compile({
  name: "string",
  age: "number",
});

console.log(check({ name: "Erf", age: 18 }));
console.log(check({ name: "Erf" }));
console.log(check({ name: "Erf", age: "18" }));`

this one has no issue,
pls feel free to close the issue

**Comment by erfanium** [comment]
I have no problem with that
look at this:
[](https://repl.it/join/ygpxjmrx-erfanium)

**Comment by hemedani** [comment]
I have the same issues and this `cdn` fix the problem : `https://cdn.pika.dev/fastest-validator@^x.x.x`
