### ISSUE TITLE
convert true to boolean don't actual converts the value.

### ISSUE THREAD

**Issue by prieston** [icebob/fastest-validator#15]
Convert boolean values as I see from the boolean.js lib it only returns true and not converting the value

**Comment by icebob** [comment]
Yes, currently it is just a validation. Don't modify the values. Only convert values for checking.

**Comment by Prieston** [comment]
Ok so will it be supported in future releases?

**Comment by icebob** [comment]
I think yes. it will be implemented.

**Comment by andersnm** [comment]
What could this look like, API-wise? And should it mutate or clone the input?

My WIP sanitize branch adds a new parameter to the validator functions, where a sanitized clone of the input is returned. F.ex:

```js
const v = new Validator();
const converted = {};
const res = v.validate(data, schema, converted);
// the sanitized data is now in converted.value
```

This leaves the API backwards compatible and mostly unchanged. A maybe nicer, but breaking change could use the return value:

```js
const v = new Validator();
const errors = [];
const converted = v.validate(data, schema, errors);
// the sanitized data is now in converted
// if converted is null, validation failed and the errors array contains the error messages.
```

Both scenarios handle when the input is a primitive type like string or number.
