### ISSUE TITLE
Review my code

### ISSUE THREAD

**Issue by erfanium** [icebob/fastest-validator#157]
@icebob 
I solved this issue #155, but I accidentally pushed this https://github.com/icebob/fastest-validator/commit/e20fa7085e78669b99d136b2a0a36d503fbcf932 commit into `icebob/fastest-validator` instead my fork -> PR.
I don't know how to revert it without create an another commit, so please check that commit changes or revert that commit.

Sorry😬

**Comment by icebob** [comment]
No problem, but in the future, please push codes in a different branch and make a PR that I can check it. 👍 

I will check it later, but LGTM at first sight.

As I see, The custom check function moved from rules to common validator?

**Comment by erfanium** [comment]
@icebob yes, 
and rules custom functions now addressed by `ruleIndex` instead of `pathName`, because sometimes some rules can have same `pathName` but with different custom check function. (for example in `multi` rule, every child rule has same `pathName`).
