### ISSUE TITLE
Generate full schema

### ISSUE THREAD

**Issue by benjick** [icebob/fastest-validator#158]
Is it possible to generate a full schema from the supplied one?

I'm thinking something like this:

```
const schema = {
    password: "string|min:6",
}
console.log(v.generate(schema))
```

result:

```
{
    password: { type: "string", min: 6 },
};
```

**Comment by icebob** [comment]
Try it. https://repl.it/@icebob/fastest-validator-convert
But please note, it is not a public method, so maybe it can be changed in the future.

**Comment by benjick** [comment]
@icebob thank you! Just what I needed 🙏
