### ISSUE TITLE
TypeError: v.alias is not a function

### ISSUE THREAD

**Issue by benjick** [icebob/fastest-validator#159]
When trying to add an alias I get this error: `TypeError: v.alias is not a function`

```js
const Validator = require("fastest-validator");
const v = new Validator();

v.alias('image', {
  type: 'string',
});
```

REPL: https://repl.it/repls/EasygoingCumbersomeProgrammers  
Version: 1.4.2

**Comment by erfanium** [comment]
Check your package.json:
```json
 "fastest-validator": "^1.0.0"
```
You are using v1.0.0

**Comment by benjick** [comment]
@erfanium thank you, I was tricked by the REPL UI 🤦 

<img width="228" alt="Skärmavbild 2020-06-15 kl  23 20 06" src="https://user-images.githubusercontent.com/430872/84707350-d4312a80-af5e-11ea-8bd7-a3beaeedc9fc.png">
