### ISSUE TITLE
Is async custom vlidation supported?

### ISSUE THREAD

**Issue by alisherafat01** [icebob/fastest-validator#16]
For example checking uniqueness of username from db.
`
v.validate(toValidate, schema).then().catch(validationErrors);
`

and using Promise for writing custom validation rule.

**Comment by njbotkin** [comment]
I've created a fork that is async-only.  Because of the overhead that promises add, I doubt it will ever be in the interests of this library to support async validation.  I'd love to be wrong, though!  https://github.com/njbotkin/fastest-validator-async

**Comment by ansarizafar** [comment]
@icebob Support for async custom validation will make this library an ideal choice for data validation. Please consider adding this feature ASAP.

**Comment by icebob** [comment]
To support async validation is a very big breaking change, so I don't think so I will add it to this repo. Better to create a fork under a new repo name and implement async to this new fork, like @njbotkin
