### ISSUE TITLE
Recursive/reference schema compilation error

### ISSUE THREAD

**Issue by fider-apptimia** [icebob/fastest-validator#168]
Version:
"fastest-validator": "^1.5.1"

Below code:
```ts
  const theA = {};
  const theB = {};
  Object.assign(theA, {
    p1: { type: 'number',  integer: true, },
    p2: { type: 'object',  props: {
      sub1: { type: 'string',  empty: false },
    } },
    $$strict: true,
  });
  
  Object.assign(theB, {
    sub: { type: 'object',  props: {
      ref: { type: 'object',  props: theA },
    } },
    $$strict: true,
  });
  const check1 = v.compile(theA)
  const check2 = v.compile(theB) // ERROR
```

Throws error:
Invalid 'undefined' type in validator schema.

**HINT - when using module [fastest-validator-modified-test](https://www.npmjs.com/package/fastest-validator-modified-test) @ 0.8.18** all is ok and **check** function is working as expected.

**Comment by erfanium** [comment]
@fider-apptimia It's not a recursive Object, Your schema is incorrect, You can use `$$strict` only when `$$root` is `true`, so you should use `strict` key in super-object instead:
```js
Object.assign(theA, {
    p1: { type: 'number',  integer: true, },
    p2: { type: 'object',  props: {
      sub1: { type: 'string',  empty: false },
    } }
  });
  
  Object.assign(theB, {
    sub: { type: 'object',  props: {
      ref: { type: 'object',  props: theA,  strict: true, },
    } },
    $$strict: true,
  });
```

**Comment by erfanium** [comment]
@icebob May we add better and more eloquent error-handler for this

**Comment by icebob** [comment]
Yeah, we should throw a correct message, that the $$strict can be used in the root level with `$$root: true` property.

**Comment by fider-apptimia** [comment]
Thanks for quick response.

Basing on above example, Is there any way to compile validator for schema `theA` and `theB` in $$strict mode assuming that as `props` I will use reference to `theA`?

**Comment by erfanium** [comment]
@fider-apptimia Why don't you use `aliases` instead? I don't understood why you are using `Object.assign` , ....

**Comment by fider-apptimia** [comment]
I was not aware of `aliases`, thank you for hint, but it not helped.

I am generating validators from custom language code like below:
```
data theA {
  p1: int, min 1, max 6;
  selfRef?: theA;
}

data theB {
  sub: {
    otherObj: theA;
  };
}
```

Generated output:
```js

const validators = Object.create(null);
const schemas = Object.create(null);
schemas['theA'] = {};
schemas['theB'] = {};

Object.assign(schemas['theA'], {
  p1: { type: 'number',  integer: true, min: 1, max: 6 },
  selfRef: { type: 'object', optional: true, props: schemas['theA'] },
  $$strict: true,
});

Object.assign(schemas['theB'], {
  sub: { type: 'object',  props: {
    otherObj: { type: 'object',  props: schemas['theA'] },
  } },
  $$strict: true,
});

validators['theA'] = v.compile(schemas['theA']);
validators['theB'] = v.compile(schemas['theB']);

return validators;
```

Any ideas how to achieve it? How to ensure `$$strict` and be prepared for references and self references?

**Comment by erfanium** [comment]
@fider-apptimia 
Cool, I think you are compiling the code with the wrong logic, for example:  `schemas['theA']` is not a valid schema, because It has no type. I suggest you to compile like this:

```js
const validators = Object.create(null);
const schemas = Object.create(null);

function rootCompile(schema) {
  return v.compile({
    $$root: true,
    ...schema
  })
}

schemas['theA'] = {};
schemas['theB'] = {};

Object.assign(schemas['theA'], {
  type: "object",
  strict: true,
  props: {
    p1: { type: 'number',  integer: true, min: 1, max: 6 },
    selfRef: { type: 'object', optional: true, props: schemas['theA'] },
  }
});

Object.assign(schemas['theB'], {
  type: "object",
  strict: true,
  props: {
    sub: { type: 'object',  props: {
      otherObj: { type: 'object',  props: schemas['theA'] },
    } },
  }
});

validators['theA'] = rootCompile(schemas['theA']);
validators['theB'] = rootCompile(schemas['theB']);

return validators;
```js

**Comment by fider** [comment]
Great, thank you.

Regards!

**Comment by erfanium** [comment]
@fider Thanks
Can I close this issue?

**Comment by fider-apptimia** [comment]
Closing now (previous comment is my priv account).

Regarding compiler, I am working on language for web services definition.
It is in early development stage, I will publish first version in 2 months (need a lot of stuff to do like documentation, VSCode syntax higliht plugin, html generator for api, browser api client generator and some other features for beta release). 

Briefly, something like below:
```
import * as x from 'url or file';

service A {
  api: {
    doA(payloadOne): x.payloadTwo
  }
}

data payloadOne { ... }
```

will compile to JavaScript + TypeScript typings.
It will generate and expose function that will force user to implement only business logic in endpoints. Data validators, call helpers with typings for other services, streams, transport protocol, backend framework etc. will be transparent for API user.
I am also planing to generate typed Browser API Client for beta.

**Comment by erfanium** [comment]
@fider-apptimia Why you don't use Typescript decorators? #169 It's much easier to create a new language.

**Comment by fider-apptimia** [comment]
@erfanium I am compiling Svc directly to JS and separately creating .d.ts files with interfaces when required.
I wanted to avoid compilation to TypeScript and then next compilation to JS.

Btw. idea of compilation from Svc to TypeScript is nice because tsc compilation will introduce additional test layer for code generators.
