### ISSUE TITLE
TS Decorators

### ISSUE THREAD

**Issue by erfanium** [icebob/fastest-validator#169]
Like https://github.com/typestack/class-validator

```ts
class User {
   @StringRule({ min: 3, max: 30 })
   name: string

   @EmailRule({ optional: true })
   email?: string
}

const check = v.compileClass(User)
```

**Comment by icebob** [comment]
It will be inside this project or a different project like `fastest-validator-decorators`?

**Comment by erfanium** [comment]
@icebob It's pretty simple to add this feature in this project, But I have to add `reflect-metadata` dependency (for define metadata in class). so may better it will be inside a `Plugin`.

**Comment by icebob** [comment]
Ohh. I want to keep FV to be dependency-free. In this case, the decorator should be created in another repo.

**Comment by erfanium** [comment]
@icebob Maybe It can be done by using `WeakMap` instead of `reflect-metadata`
