### ISSUE TITLE
Nested Convert does not work.

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [icebob/fastest-validator#172]
I'm using this package with Moleculer. Specifically I'm using the `^1.5.1` version of fastest-validator. When I try to specify this kind of item in the validator:
```javascript
{test: {type: 'array', items: {type: 'number', integer: true, positive: true, convert: true}}}
```
an array of this kind:
```javascript
{test: [1, "2"]}
```
passes the validation without getting the `"2"` converted to number... 
Without `convert` the item gets correctly refused.

**Comment by erfanium** [comment]
@icebob I don't have free time for a short time, If you can, follow this up. Thanks!

**Comment by icebob** [comment]
OK, I will check it.

**Comment by icebob** [comment]
It works in the latest version.
![image](https://user-images.githubusercontent.com/306521/118989500-60737b00-b982-11eb-9b6f-40746f44e574.png)

**Comment by HighSoftWare96** [comment]
Ok
I haven't seen that in the picture: the second item gets converted?

**Comment by icebob** [comment]
Ohhm, I don't check it, just that it returns `true` :)

**Comment by icebob** [comment]
Yeah, it converted:
![image](https://user-images.githubusercontent.com/306521/119012907-bfdb8600-b996-11eb-94fc-83e1117a4167.png)
