### ISSUE TITLE
Add AdditionalProperties?

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [icebob/fastest-validator#173]
Is there a way to specify additional properties for an object? Like this:
```javascript
  filter: {
    type: 'object',
    props: {
      channels: {
        type: 'object',
        props: {
          '*': {
            type: 'array'
          }
        }
      }
    }
  }
```

so I can validate an object like this:
```javascript
{filter: {channels: {a: [1, 2, 3], b: [1, 2, 3], "1": [1] }}}
```

**Comment by erfanium** [comment]
@giovanni-bertoncelli Currently not ,But you can use custom validator for this case.

**Comment by giovanni-bertoncelli** [comment]
Ok, in the end I've used that... Should I close this or can it be a useful feature?

**Comment by giovanni-bertoncelli** [comment]
@icebob @erfanium Can you please consider this feature? This is a standard in JSON Schema and it can be very helpful.

**Comment by erfanium** [comment]
@giovanni-bertoncelli checkout #276

that's planned but somebody should implement it
