### ISSUE TITLE
[Question/Bug?] Trim: true is a noop for type: email (and pattern)

### ISSUE THREAD

**Issue by hummingbirdcommerce** [icebob/fastest-validator#174]
Hi @icebob,

Firstly, thank you for this great, high-quality library. Fantastic to see a zero-dependency 100% test coverage library in the JS ecosystem!

The following may not be an issue, but I just wanted to check if the below is intended behavior for the library. If it is, I can help clarify with a documentation tweak PR or, if it's not intended, I can help implement a fix.

In the email tests in `test/rules/email.spec.js` starting on line 45 (`should check values`), you'll see that the assertion I added to line 58 is failing because the email address has spaces either side of it. Even though `trim: true` was passed in as an option at the compilation stage (line 46), the sanitizer appears to not trim the input prior to running the email pattern check. The same behavior occurs for the `pattern` type, but I wanted to keep the example here simple (limited to the `email` type) to check my basic understanding of how the `trim` sanitizer should work:

![image](https://user-images.githubusercontent.com/58406631/86255160-a0175580-bb6b-11ea-97a8-692e814798c2.png)

It's quite common to trim user input coming in from the clientside, as often users will leave trailing spaces etc from copy + pasting their email addresses from where ever they get their email address from these days :) 

My question is: would you expect `trim: true` to work with the `email` type? If so, would it help if I issue a PR (inc tests) to implement this behavior?

Please lmk! Thanks! :)

**Comment by erfanium** [comment]
@hummingbirdcommerce You should use `normalize` property: https://github.com/icebob/fastest-validator#email

**Comment by hummingbirdcommerce** [comment]
@erfanium perfect, thank you for the pointer and quick response! That does indeed work as expected :) Closing this comment. Thanks again!
