### ISSUE TITLE
TypeError when using type: "any" 

### ISSUE THREAD

**Issue by SockeThe2nd** [icebob/fastest-validator#184]
I am getting `TypeError: context.fn[1] is not a function` when using type any. 

I condensed my code down to the example below, which still throws an error.
```JS
const inner = { type: "any" };

const schema = {
	prop1: inner,
	prop2: inner
};
const check = v.compile(schema);

var values = {
	prop1: "value1",
	prop2: "value2"
};

var result = check(values); 
//should be true but throws 
//TypeError: context.fn[1] is not a function
```

When using a different type instead of "any" (like "string"), the example works as expected. Additionally, when defining the schema directly (see below) the any-type works as well.

```JS
const schema = {
	prop1: { type: "any" },
	prop2: { type: "any" }
};
const check = v.compile(schema);

var values = {
	prop1: "value1",
	prop2: "value2"
};

var result = check(values); //Works as expected
```

**Comment by erfanium** [comment]
@icebob Found it, I'll fix it

**Comment by icebob** [comment]
Thanks, @erfanium

**Comment by erfanium** [comment]
@SockeThe2nd This problem was most likely solved, Can you text again?

**Comment by SockeThe2nd** [comment]
@erfanium Can confirm. My code above works with the current master-branch. Thank you very much for the quick fix.
