### ISSUE TITLE
boolean field must be true

### ISSUE THREAD

**Issue by mtcarvalho** [icebob/fastest-validator#192]
I am passing one Laravel project to Moleculer.js. Now, I have to pass the Laravel [accepted](https://laravel.com/docs/5.0/validation#rule-accepted) field to Moleculer.js using fastest-validator. Is there any built-in validator that already does this? I didn't found in docs.

**Comment by erfanium** [comment]
@mtcarvalho There's no such feature, but you can make your own custom rule https://github.com/icebob/fastest-validator#custom-validator

**Comment by erfanium** [comment]
I personally don't like this, because JSON explicitly supports Boolean and there is no reason to use a number or string instead

**Comment by icebob** [comment]
Use the `equal` rule: https://github.com/icebob/fastest-validator#equal

**Comment by mtcarvalho** [comment]
thanks @icebob, this rule is exactly what I need
