### ISSUE TITLE
Support Nil UUID

### ISSUE THREAD

**Issue by uasan** [icebob/fastest-validator#200]
Hello.
Nil UUID is not currently supported, but it is a valid value:
https://tools.ietf.org/html/rfc4122#section-4.1.7

Are these validator behaviors by design?
If yes, then maybe  to allow, if add new bool property `zero` or `nil`

```JS
{
  type: 'uuid',
  zero: true
}
```

Thanks.

**Comment by intech** [comment]
@uasan greetings! In which case may you need to validate different uuid versions?
I suggest just adding version 0 and specifying it in the validation rule. Is this an option?

**Comment by uasan** [comment]
> I suggest just adding version 0 and specifying it in the validation rule. Is this an option?

No ), for me case, rules validate UUID values of version: 4 or 5 or Nil UUID.
Nil UUID - this is one exceptional value, that should not be limited to versions.

**Comment by intech** [comment]
@uasan everything is fine, I didn't immediately remember that I determine the version from the uuid itself, so it doesn't matter which one to transfer.
Now I will correct the tests and wait for the merge. After that there will be support is nil uuid.
And thanks for the good point! It is important to maintain rfc.

**Comment by icebob** [comment]
Published.
