### ISSUE TITLE
Out of the box support for Express

### ISSUE THREAD

**Issue by FroxTrost** [icebob/fastest-validator#205]
🙌🏼 First of all thanks for the awesome library. 👏🏼 
I"ve used fastest-validator in a couple of my past projects and It has been a wonderful experience.

Lately, I've been working with [Express](https://github.com/icebob/fastest-validator/issues/new) and thought of using fastest-validator as a lib to validate requests.
I used the fastest-validator as a middleware to validate the API requests and it has been a great experience.

If you think this functionality can be provided out of the box in the library, I will be happy to create a PR.

Thanks

**Comment by erfanium** [comment]
You can create a express middleware in separate repository, (I have done this for Fastify before: https://github.com/erfanium/fastify-fv)

**Comment by FroxTrost** [comment]
Sure, will create a separate repo for it.
Thanks

**Comment by Faridalim** [comment]
@FroxTrost , @erfanium Hi, i am sorry since it is 3 years late but nice discussion. I am wondering if if it would be better for us to compile all schemas at once when starting server? or is it doesnt really make any difference if we compile schemas on each request?

**Comment by erfanium** [comment]
@Faridalim compiling schemes on each request will make fastest-validator to slowest-validator-ever

**Comment by Faridalim** [comment]
> @Faridalim compiling schemes on each request will make fastest-validator to slowest-validator-ever

Hm, but i have seen your and FroxTrost implementations. It seems that both of you add the validator in the middleware. Is that not compiling schemes in each request?

**Comment by erfanium** [comment]
@Faridalim you mean my fastify plugin? It will only compile the schemes once per app initialization. It's not per request.
