### ISSUE TITLE
How can i xor fields on my schema

### ISSUE THREAD

**Issue by hadasmeitav** [icebob/fastest-validator#208]
say i have a schema : 
```
const schema = {
        field1: { type: 'number', integer: true },
	field2: { type: 'number', integer: true }
}
```
I'd like to have the ability to have a xor between those 2 fields.
For example, if field1 > 0, i want to validate that field2 > 0.

I'd expect something like a shared rule between the fields, but i couldn't find reference to fields combination rules.
```
const schema = {
        field1: { type: 'number', integer: true },
	field2: { type: 'number', integer: true },
        rules: [...]
}
```

Any one knows if this is possible using this library?
I see that [this pr](https://github.com/icebob/fastest-validator/pull/206) is handling my scenario.

**Comment by icebob** [comment]
Currently it is not available, only with custom rules.

**Comment by erfanium** [comment]
Stale
