### ISSUE TITLE
Labels In Error Messages Instead of Property Names

### ISSUE THREAD

**Issue by valeeum** [icebob/fastest-validator#209]
Here is an example of current error message: 

`The 'email_address' field must not be empty.`

Is there a way to pass field label into schema so the error message is displayed like so: 

`The 'Email Address' field must not be empty.`

I know we can use custom messages for each field but curious if there's a lazier approach here :)

**Comment by erfanium** [comment]
Hi
I think displaying  `label` in APIs instead of real property name is not good idea in general. What is the main reason you need this feature? Do you use fastest-validator from server-side?

**Comment by valeeum** [comment]
@erfanium 

For this particular use case, I'm using it client side for form validation. 

![image](https://user-images.githubusercontent.com/1195356/103030746-4176d700-4511-11eb-95fb-9cce73624b5d.png)

**Comment by icebob** [comment]
Workaround: use custom `messages` in the rules.

**Comment by erfanium** [comment]
@icebob It's not a good solution, for example look at string rules messages:

Name                | Default text
------------------- | -------------
`string`	| The '{field}' field must be a string.
`stringEmpty`	| The '{field}' field must not be empty.
`stringMin`	| The '{field}' field length must be greater than or equal to {expected} characters long.
`stringMax`	| The '{field}' field length must be less than or equal to {expected} characters long.
`stringLength`	| The '{field}' field length must be {expected} characters long.
`stringPattern`	| The '{field}' field fails to match the required pattern.
`stringContains`	| The '{field}' field must contain the '{expected}' text.
`stringEnum`	| The '{field}' field does not match any of the allowed values.
`stringNumeric`	| The '{field}' field must be a numeric string.
`stringAlpha`	| The '{field}' field must be an alphabetic string.
`stringAlphanum`	| The '{field}' field must be an alphanumeric string.
`stringAlphadash`	| The '{field}' field must be an alphadash string.
`stringHex`	| The '{field}' field must be a hex string.
`stringSingleLine`	| The '{field}' field must be a single line string.

We will probably have to customize a lot of these messages for a single field.
I think `label` field is more convenient way:

```js
schema = {
    emailAddress: { type: "email", label: "Email Address" }
}
```

**Comment by stfullstack** [comment]
I also think this would be a useful feature. You could have it default to the {field} unless you have provided the label.

**Comment by icebob** [comment]
We can't change the `{field}` to `{path}` because it cause breaking change. But for the label feature, we welcome PRs.
