### ISSUE TITLE
Add simple enum validator (that can be any of type)

### ISSUE THREAD

**Issue by evilandfox** [icebob/fastest-validator#21]
Hi! Thanks for your great tool) 
I think "enum" validator will be very userful. At this time this is available for string validator. But, for example, I often use numeric enums in REST API as parameters.
I know that it can be made by using multiple validators. But that will be great to write like:
```
let schema = {
    status: { type: "enum", values: [null, 1, 2, "done"] }
}
v.validate({ status: "done" }, schema)
```

**Comment by icebob** [comment]
Good idea. Currently I have no time to implement it. If you think, you can create a PR. You should create a similar rule as [string rule](https://github.com/icebob/fastest-validator/blob/master/lib/rules/string.js)

**Comment by evilandfox** [comment]
Ok, I'll try to do so
