### ISSUE TITLE
Email min max?

### ISSUE THREAD

**Issue by slidenerd** [icebob/fastest-validator#211]
- First of all thank you for the fantastic work on this library
- As per [THIS](https://stackoverflow.com/questions/386294/what-is-the-maximum-length-of-a-valid-email-address) discussion, it seems email seems to have an upper limit of 320
- But currently min and max properties dont work with email
- Would it be possible to do something about this
`
var s = {email: {type: 'email', min: 3, max: 320, lowercase: true}}
email = 'abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQESTUVWXYZabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQESTUVWXYZabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQESTUVWXYZabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQESTUVWXYZ@gmail.com'
v.validate({email}, s) //prints true
`

**Comment by icebob** [comment]
Yeah, good idea to implement min/max param for "email" rule. Could you create a PR?
