### ISSUE TITLE
Combine multiple validators with optional?

### ISSUE THREAD

**Issue by rulatir** [icebob/fastest-validator#212]
Is it possible to express the idea that a field is optional, but when it is present then it must satisfy one of multiple validators?

As I understand the docs, the property descriptor can either be an object (representing a single validator that can have "optional" field) or an array (containing multiple such validators). In the latter case there seems to be no way to "attach" the optionality information to that array as a whole. Am I overlooking something?

**Comment by icebob** [comment]
You can use two ways:

```js
{
    status: [
        { type: "string", optiona: true },
        { type: "boolean", optiona: true },
    ]
}
```

or 
```js
{
    status: { type: "multi", optional: true, rules: [
        { type: "string" },
        { type: "boolean" },
    ] }
}
```

**Comment by rulatir** [comment]
Thanks, I missed `"multi"` somehow.

**Comment by rulatir** [comment]
Thanks, I overlooked `"multi"` somehow.
