### ISSUE TITLE
uuid validation

### ISSUE THREAD

**Issue by uniquedevs** [icebob/fastest-validator#216]
00000000-0000-0000-0000-00000000001b  fastest-validator suggests this "uuid" is NOT valid, even though it is valid based on 128 bit number. Postgres for example assumes it is valid.

**Comment by erfanium** [comment]
@icebob 
I think current UUID regex has problem, this one seems good:
```js
/^([0-9a-f]{8}-[0-9a-f]{4}-[1-6][0-9a-f]{3}-[0-9a-f]{4}-[0-9a-f]{12}|[0]{8}-[0]{4}-[0]{4}-[0]{4}-[0]{12})$/i 
```

**Comment by icebob** [comment]
@intech could you check this issue?

**Comment by intech** [comment]
@uniquedevs uuid check is strictly according to [rfc4122](https://tools.ietf.org/html/rfc4122)
Your example does not match any of the uuid versions, so the check fails.
I would suggest using regex validation for uuid not matching rfc

```js
{ type: "string", pattern: /^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$/i }
```

**Comment by intech** [comment]
And, in postgres uuid-ossp support only 1,3,4,5 version in [docs](https://www.postgresql.org/docs/current/uuid-ossp.html#id-1.11.7.53.5).

> Table F.32 shows the functions available to generate UUIDs. The relevant standards ITU-T Rec. X.667, ISO/IEC 9834-8:2005, and RFC 4122 specify four algorithms for generating UUIDs, identified by the version numbers 1, 3, 4, and 5. (There is no version 2 algorithm.) Each of these algorithms could be suitable for a different set of applications.

**Comment by uniquedevs** [comment]
@icebob rfc4122 describes algorithms for generating different versions of UUID. From postges documentation "A UUID is written as a sequence of lower-case hexadecimal digits, in several groups separated by hyphens, specifically a group of 8 digits followed by three groups of 4 digits followed by a group of 12 digits, for a total of 32 digits representing the 128 bits." That's why I suggest that if I don't specify a certain version of uuid algorithm, then I want to validate a sequence of hexadecimal digits representing 128  bits. 00000000-0000-0000-0000-00000000001b is a valid UUID for postgres. of course, I can use a string pattern otherwise. Anyway, thanks for the quick feedback! )

**Comment by intech** [comment]
@uniquedevs the difference is that UUID is a structured record. That is why it cannot be arbitrary. Each version has its own checking features, and the version itself is indicated in 3 section 1 character.

00000000-0000-**0**000-0000-00000000001b
In your example version 0, by RFC it can only be UUID Nil when all values are zero. There are no other descriptions there.

As for postgres, then, most likely, we are talking about storing data, all databases with which I worked do not check the version of the UUID, since they store it in a binary format of 16 bytes to reduce the size of the index. And the output uses a 32-byte hexadecimal representation with a breakdown into groups.

**Comment by uniquedevs** [comment]
@intech ok, got it. My opinion is you should better update the documentation a little - remove support of uuid version 0 (except Nil). it leads to misunderstanding. It's not critical of course. Thanks for the feedback!

**Comment by icebob** [comment]
Maybe (similar to other rules) we can use a `strict` property to turn on/off the version checking. And if `strict: false` we checks only the regex matching.

**Comment by intech** [comment]
@icebob we can. But, this will no longer be a uuid - that's what I was trying to explain.
