### ISSUE TITLE
nonNegative [0... ∞) for number

### ISSUE THREAD

**Issue by hugebdu** [icebob/fastest-validator#217]
shouldn't [be there](https://github.com/icebob/fastest-validator#properties-9)?
I have a use case. cannot see how to achieve it without custom validator.

can try & PR if you think there's a place for it

10x

**Comment by icebob** [comment]
`{ type: "number", min: 0 }` gives the same result.

**Comment by hugebdu** [comment]
indeed.
this is... embarrassing

10x
