### ISSUE TITLE
feature: support for object.propValidator

### ISSUE THREAD

**Issue by hugebdu** [icebob/fastest-validator#219]
Currently `object` built-in validator [supports only](https://github.com/icebob/fastest-validator#properties-10) `minProps` and `maxProps`.

I have a use case where I need to further check object properties (regexp) - both the keys and the values (dictionary). I found a work-around with a custom validator, inspired by [this one](https://github.com/icebob/fastest-validator/issues/108#issuecomment-725581240) but seems like a valid feature.

I can try & PR if you think it makes sense.

btw same applies to object values.

10x.

**Comment by icebob** [comment]
Why would be it's different from the custom `check` method?

**Comment by hugebdu** [comment]
actually what I need here is another type - `map`.
ended up [implementing it as a rule](https://gist.github.com/hugebdu/f1881bd246a6787a5d6e5d60c7fffbe9#file-map-js-L32), looks like does the job.

```
// usage example
const schema = {
  mapField: {type: 'map', keyPattern: /d+/, min: 2, items: {type: 'string}},
}
```
