### ISSUE TITLE
Multiple validators not working with objects

### ISSUE THREAD

**Issue by mauricedoepke** [icebob/fastest-validator#22]
It seems like multiple validators are not working properly when they are objects.
Here is an example:

```
const field = {
    type: 'object',
    props: {
        type: {
            type: 'string',
            pattern: /^field$/
        },
        fieldId: {type: 'number', positive: true, integer: true},
        title: {type: 'string', min: 4, max: 50, optional: true},
        values: {
            type: 'array',
            items: {type: 'string', min: 1, max: 50}
        }
    }
};

const seperator = {
    type: 'object',
    props: {
        type: {
            type: 'string',
            pattern: /^seperator$/
        }
    }
};

const col = {
    type: "array",
    min: 1,
    max: 4,
    items: [
        field,
        seperator
    ],
};

const schema = {bla: col};
console.log(validator.validate({bla:[{"type": "sfdf"}]}, schema));
```

I expect this validation to fail, but it succeeds. It seems like it only checks whether the array contains an object, but does no further validation regarding the properties.

With other types than objects it is working properly, example: 

```
const col = {
    type: "array",
    min: 1,
    max: 4,
    items: [
        {type: 'boolean'},
        {type: 'string', min: 5}
    ],
};

const schema = {bla: col};
console.log(validator.validate({bla:["sfdf"]}, schema));
```
Fails as expected because the string is to short.

And for a single validator, everything is working fine, too:

```
const col = {
    type: "array",
    min: 1,
    max: 4,
    items: field
};
```

**Comment by icebob** [comment]
Yes, it doesn't work because multiple validator expects different types.

**Comment by mauricedoepke** [comment]
If I understand your code right, the problem is, that the validation of an object is internally broken up into two rules. First: Whether typeof === 'object' and second: recursively checking the props.

```
checks.push({
	fn: this.rules[rule.type],
	type: rule.type,
	name: name,
	schema: rule,
	iterate: iterate
});

// Nested schema
if (rule.type === "object" && rule.props) {
	// Compile the child schema
	checks.push({
		fn: this.compile(rule.props),
		type: rule.type,
		name: name,
		schema: rule,
		iterate: iterate
	});
}
```

But the checkerWraper already aborts after one 'internal' rule is valid in a multirule case.
This means that the bug applies to checking of arrays two, because they are also broken up into two internal rules.

I see two ways for fixing this, both are not very nice.

1) 
Handling objects and arrays as a singletypeof rule in the main code, like for example the string rule and doing the recursion in the rule itself. Which could be done through calling the validation function of the library from the rule itself with only the recursive part of the schema.
This however would severley complicate handling of error messages.

2)
Handling them as a special case in the checkWrapper. This would mean if we normally drop out because one rule is valid, we check whether it is an array or object rule and force the checkWraper to also validate the recursive rule which directly follows the simple typeof rule.
This however would break a little with your architecture of having the rules as kind of of plugins.
Although youre already breaking with this by breaking these rules up into two.

I would go with the second method as this would only mean to add one state variable and a i condition.

What do you think about that?

**Comment by icebob** [comment]
Yes, the second method sounds better. Maybe do you try to fix it in a PR?
