### ISSUE TITLE
Feature : Nested Schema

### ISSUE THREAD

**Issue by dannyfoncke** [icebob/fastest-validator#223]
How can I include a schema in a schema ?
I'm trying to add a custom type to a schema A, where that custom type refers to another schema B
I add that custom type to the validator of schema A (v.add) and in the function I try to call the validate function of the module where schema B is validated
For that I need to import (require) the schema B validate function, but that doesn't seem to work
Can it be done ? (this or any other way ) thanks

**Comment by AndreMaz** [comment]
Please check [aliases](https://github.com/icebob/fastest-validator#alias-definition)

**Comment by dannyfoncke** [comment]
I guess it probably should but I can't get it to work
What I'm trying to do 

I have 'master' 
```
        schema: = {
		Type: { type: "string" },
		Config: { type: "Cron.v1" },
	};
```
the Cron.v1 is 
```
schema = {
	Schedule: { type: "string" }
};
```
The validation happens on the 'master' schema : 
with the cronSchema schema imported from another module
 ```
const v = new Validator(messages);
	v.alias('Cron.v1', cronSchema);
	return v.validate(obj, schema)
```
The system finds the alias, and does a deepextend
```
               if (alias) {
			delete schema.type;
			schema = deepExtend(schema, alias, { skipIfExist: true });
		}
```
The return schema of that is : 
```
{
	Schedule: { type: "string" }
  };
```
after which the following throws an error
```
const ruleFunction = this.rules[schema.type];
		if (!ruleFunction)
			throw new Error("Invalid '" + schema.type + "' type in validator schema.");
                }
```
because schema.type is undefined (it has : { Schedule : { type: string})

**Comment by erfanium** [comment]
@dannyfoncke 
Please reproduce it in another repo if you think it's a bug.

### Notes:
```js
const v = new Validator(messages);
v.alias('Cron.v1', cronSchema);
return v.validate(obj, schema)
```

1. Never ever use `v.validate`, just compile schema via `v.compile` *only once*, and validate the object with checker function:
https://github.com/icebob/fastest-validator#validate

2. 99% of time, You don't need to create multi instance of Fastest-validator. use singleton pattern

**Comment by dannyfoncke** [comment]
OK, used it with Typescript (should've done that immediately)

One can't pas a schema as alias
Nested object is what I need to use.
Which works :) 
Thanks for the prompt replies, sorry to have wasted some of your time 
Keep up the good work
