### ISSUE TITLE
Email Validation Bug - When Empty Property Is False And Value is Empty String

### ISSUE THREAD

**Issue by valeeum** [icebob/fastest-validator#224]
When schema entry for email field has "empty" property set to false, value is coerced into number.   

https://runkit.com/embed/24rdibzy73yz

```
var fastestValidator = require("fastest-validator");

const v = new fastestValidator();
const values = {someEmailField: ""};
const schema = {
    someEmailField: {
        type: "email",
        empty: false,
    }
};

const validationResult = v.validate(values, schema);
console.info({values});
```

Here is the output from runkit (link listed above):

![image](https://user-images.githubusercontent.com/1195356/111494567-d1d14c00-86fb-11eb-903e-22a4122d2cae.png)

**Comment by erfanium** [comment]
It's not really a bug. because `validationResult` is not true and there's validation errors. Why you want to use `values` object when you know this object is not valid?

**Comment by valeeum** [comment]
Maybe I'm using this package in ways it wasn't intended but I'm using it for basic frontend form validation in addition to using it for our moleculerjs based backend.  We validate and sanitize (if necessary) as the user types.   I was not expecting values to be mutated if sanitizers weren't enabled.  You can always clone, validate then revert if failed but I think it's better to not mutate values when possible.   

![image](https://user-images.githubusercontent.com/1195356/111500932-c08b3e00-8701-11eb-916f-d77ed6c5dfe3.png)
