### ISSUE TITLE
potential uuid validation bug

### ISSUE THREAD

**Issue by arun-prakash-fokus** [icebob/fastest-validator#243]
This may be a potential uuid bug in the fastest-validator or incorrect usage of the API from my part (due to lack of expertise, in which case, kindly ignore)

I have the following moleculerjs action defined in my service.

```ts
import UUID from "uuid";
...
@Action({
    rest: {
        method: "GET",
        path: "/process/:id",
    },
    params: {
        id: { type: "uuid" },
        cache: { type: "boolean", optional: true, default: true, convert: true }
    }
})
async getFlowProcess(ctx: Context<{ id: typeof UUID, cache: boolean }>): Promise<Dto<FlowProcess>> {
 const id = ctx.params.id;
 ....
}
```

For the below uuids

```
9adabada-3b4b-32eb-fd7e-c41191eefa2a
642ff728-2fb3-3e6b-f48f-0cfb94b772e2
```
it fails with the following error message

```json
{
    "name": "ValidationError",
    "message": "Parameters validation error!",
    "code": 422,
    "type": "VALIDATION_ERROR",
    "data": [
        {
            "type": "uuid",
            "message": "The 'id' field must be a valid UUID.",
            "field": "id",
            "actual": "9adabada-3b4b-32eb-fd7e-c41191eefa2a",
            "nodeID": "sqc-x1-xtrm-apr-21964",
            "action": "v1.dataflow.getFlowProcess"
        }
    ]
}
```

I validated the correctness of this uuid on 

https://www.freecodeformat.com/validate-uuid-guid.php

![image](https://user-images.githubusercontent.com/25454690/120997380-6f7e6980-c787-11eb-8d85-54809207c96c.png)
 
 I tried to provide the `uuid` `version` property as follows and tried it with various values ranging from `0-5`
 
 ```ts
    params: {
        id: { type: "uuid", version: 3 },
        cache: { type: "boolean", optional: true, default: true, convert: true }
    }
 ```
 
 For all cases, except `version: 3`, i get the following error response (e.g, when I set `version: 4`):
 
 ```json
 {
    "name": "ValidationError",
    "message": "Parameters validation error!",
    "code": 422,
    "type": "VALIDATION_ERROR",
    "data": [
        {
            "type": "uuidVersion",
            "message": "The 'id' field must be a valid UUID version provided.",
            "field": "id",
            "expected": 4,
            "actual": 3,
            "nodeID": "machine-21528",
            "action": "v1.dataflow.getFlowProcess"
        }
    ]
}
```

**Comment by erfanium** [comment]
@arun-prakash-fokus What is your expected result?

> it fails with the following error message

How do you generate these UUIDs? They are not valid, because they have unknown variant. see https://www.uuidtools.com/decode for extra info

> For all cases, except version: 3, i get the following error response (e.g, when I set version: 4):

Also this is expected, because performing uuid version check is mush faster than other validations, so FV first validates the UUID version than other parts

**Comment by arun-prakash-fokus** [comment]
> @arun-prakash-fokus What is your expected result?

>>    it fails with the following error message

That the UUIDs are validated as valid.

>> How do you generate these UUIDs? They are not valid, because they have unknown variant. see https://www.uuidtools.com/decode for extra info

I am developing an API wrapper on top of NiFi. The UUIDs are generated by the NiFi application.

**Comment by erfanium** [comment]
@arun-prakash-fokus 
> That the UUIDs are validated as valid.

They are not. If you want to allow UUIDs that has unknown variant, just use this code from here.
https://github.com/icebob/fastest-validator/issues/216#issuecomment-781370967

**Comment by intech** [comment]
Sorry, did not have time to answer after reading.

@arun-prakash-fokus You wrote everything correctly, the given uuid examples are valid only for version 3 according to rfc.
Version 4 is checked by default is the most popular. I suppose you should check any version for validity by default, or use the `strict: false` parameter, or suggest your option to skip the uuid of all versions with an optional setting.

@erfanium Thanks for giving the reference. As for the option, it only matters in version 4.

As for the option, it only matters in version 4.

**Comment by intech** [comment]
9adabada-3b4b-**3**2eb-fd7e-c41191eefa2a
642ff728-2fb3-**3**e6b-f48f-0cfb94b772e2
Everything is very simple this is the version in the uuid itself

**Comment by intech** [comment]
> I am developing an API wrapper on top of NiFi. The UUIDs are generated by the NiFi application.

https://nifi.apache.org/docs/nifi-docs/html/expression-language-guide.html#uuid

**Comment by erfanium** [comment]
> it only matters in version 4.

@intech 
https://github.com/icebob/fastest-validator/blob/master/lib/rules/uuid.js#L40

It runs the variant check for version 3, 4 and 5

**Comment by intech** [comment]
> It checks the variant for version 3, 4 and 5 (Unless our implementation is wrong?)

Yes you are right, it was on rfc for 3, 4, 5 versions.

**Comment by arun-prakash-fokus** [comment]
Thank you all for your inputs.

Probably, I did not explain correctly the first time.

The UUIDs that I am checking / validating are generated by NiFi. They are:

```
9adabada-3b4b-32eb-fd7e-c41191eefa2a
642ff728-2fb3-3e6b-f48f-0cfb94b772e2
```

As per the documentation, correctly pointed out by Ivan, NiFi generates them as type 4 UUID. This is why I wrote my initial code with :

```ts
    params: {
        id: { type: "uuid" },
        cache: { type: "boolean", optional: true, default: true, convert: true }
    }
 ```
 
 as far as I understood, FV does validation of UUIDs as v4 type.
 
 Since the validation failed, I used the free online tool:
 
 https://www.freecodeformat.com/validate-uuid-guid.php
 
 to check the UUID and its type. It returned to me that the UUIDs are of v3 type.
 
 So I updated the code to:
 
 ```ts
    params: {
       id: { type: "uuid", version: 3 },
       cache: { type: "boolean", optional: true, default: true, convert: true }
   }
   ```
   
   In the first case and in the second case, I get the same error message back
   
   ```json
   {
    "name": "ValidationError",
    "message": "Parameters validation error!",
    "code": 422,
    "type": "VALIDATION_ERROR",
    "data": [
        {
            "type": "uuid",
            "message": "The 'id' field must be a valid UUID.",
            "field": "id",
            "actual": "9adabada-3b4b-32eb-fd7e-c41191eefa2a",
            "nodeID": "sqc-x1-xtrm-apr-21964",
            "action": "v1.dataflow.getFlowProcess"
        }
    ]
}
```


@intech - I check with your suggestion with `strict: false`

**Comment by intech** [comment]
> I check with your suggestion with `strict: false`

this is an unrealized functionality, I propose to implement it if there is a need for it

**Comment by erfanium** [comment]
@arun-prakash-fokus
Let me explain exactly how FV uuid validation works:

1. It checks value to to be string
2. It checks value pattern with a generic UUID regex
3. if uuid version specified, then It checks uuid version
4. if uuid version is 3, 4, 5, It checks **UUID variant** to be one of (8, 9, a, b)

No less, no more. **There is no default UUID version.**

### Example A: 
9adabada-3b4b-**3**2eb-**f**d7e-c41191eefa2a
This is a uuid v3, and variant character is `f` and `f` is not a valid uuid variant (just 8, 9, a and b are valid). **NOT VALID**

### Example B: 
eed38560-25a0-**3**a6d-**b**91b-55a711934f8e
This is a uuid v3, and variant character is `b` and `b` is a valid uuid variant. **VALID**

So your UUIDs are failed in 1variant check1 stage, it's not about version. if you want to skip this check, just validate your value via generic UUID regex pattern https://github.com/icebob/fastest-validator/issues/216#issuecomment-781370967

**Comment by arun-prakash-fokus** [comment]
@erfanium - thank you very much the explanation. I will use your proposed approach.

**Comment by arun-prakash-fokus** [comment]
@erfanium,

I also tried to check with other UUIDs generated in NiFi. 

For instance, with

`9adabada-3b4b-32eb-2689-4587dac319d0`

https://www.uuidtools.com/api/decode/9adabada-3b4b-32eb-2689-4587dac319d0

![image](https://user-images.githubusercontent.com/25454690/121179635-3f56c980-c860-11eb-94b9-be96c5fed85a.png)

This is a **VALID** UUID, right?

However, when I validate with FV, it throws me an invalid error. 

Is this behavior correct?

Thanks

**Comment by intech** [comment]
> This is a **VALID** UUID, right?

Not. Reserved but not used in actual uuid variants.

**Comment by arun-prakash-fokus** [comment]
thank you. that clarifies it.

**Comment by erfanium** [comment]
@arun-prakash-fokus 
I'm going to close this issue but if you still have questions, feel free to continue here. Thanks

**Comment by arun-prakash-fokus** [comment]
This does not concern fastest-validator strictly.

Nevertheless, I am adding an external link to the Apache NiFi's Jira board so that it helps anyone who is looking for a solution related to the UUID issues with NiFi / FV / moleculerjs.

I have the hack documented here to generate valid UUIDs inside NiFi using the _X-Cluster-Id-Generation-Seed_ header

https://issues.apache.org/jira/browse/NIFI-8669
