### ISSUE TITLE
[FEATURE] Add error hadler for 'enum' validator without values

### ISSUE THREAD

**Issue by VityaSchel** [icebob/fastest-validator#247]
If you try to validate object with this validator:

```javascript
{ type: 'enum', foobar: ['foo', 'bar'] }
```

You'll get `TypeError: Cannot read property 'join' of undefined`

I suggest adding error handler if you are not specifying `values` key in schema

**Comment by VityaSchel** [comment]
Lmao looks like maintainers doesn't give a fuck about what's going on here. I've never tried to pull-request, but maybe I'll fix this issue and open a pull request.

![image](https://user-images.githubusercontent.com/59040542/123544928-b1874380-d766-11eb-86bf-28e5ba4ff59e.png)

**Comment by VityaSchel** [comment]
I hope I did everything right, if not, please redo. Like really it's just 1 line...

**Comment by erfanium** [comment]
Just use typescript.
I tried to add schema language validator in https://github.com/icebob/fastest-validator/pull/194 long time ago, but it's more than doing some if-statement. Typescript has been created to solve exactly these problems.

**Comment by icebob** [comment]
@VityaSchel please change your tone of voice. The maintainers work on this project free of charge and in their free time. If you are not satisfied with it, fork it, and maintain your fork by yourself.

By the way, this issue is a developer error, and not a bug in the project. Similar to this, we should check all properties in all rules to ensure that the developer doesn't make typo in their code.

**Comment by VityaSchel** [comment]
> @VityaSchel please change your tone of voice. The maintainers work on this project free of charge and in their free time. If you are not satisfied with it, fork it, and maintain your fork by yourself.
> 
> By the way, this issue is a developer error, and not a bug in the project. Similar to this, we should check all properties in all rules to ensure that the developer doesn't make typo in their code.

It IS bug in the project. Error handling is a best practice, so please merge my pull request instead of closing it. I won't start a fork of this project just to fix 1 bug.

**Comment by VityaSchel** [comment]
Please merge pull request or tell me how to change this 1 line I propose to prevent any bugs so you can merge it later.

**Comment by VityaSchel** [comment]
> Just use typescript.
> I tried to add schema language validator in #194 long time ago, but it's more than doing some if-statement. Typescript has been created to solve exactly these problems.

Typescript is not an option here because it checks variables outside of fastest-validator api. What I propose is to add error handler inside of api. Obviously, I already fixed problem on my side when this error occured, I quickly figured out what was wrong and to prevent other people from this problem I decided to open this issue and even pull request. 

Why you closed it? You have so little free time that you can't click 1 button? Or my code if broken? Tell me what's wrong with pull request, I'll fix it.

**Comment by VityaSchel** [comment]
> @VityaSchel please change your tone of voice. The maintainers work on this project free of charge and in their free time. If you are not satisfied with it, fork it, and maintain your fork by yourself.
> 
> By the way, this issue is a developer error, and not a bug in the project. Similar to this, we should check all properties in all rules to ensure that the developer doesn't make typo in their code.

How about I give you an example why you wrong.

Imagine you making a request to github profile api without authentification:

![image](https://user-images.githubusercontent.com/59040542/123644047-12ca1800-d836-11eb-8447-4b3b81a3ca24.png)

Oh no! I get error in which it obviously specified that this method requires authentification. It even gives you a documentation url (similiar to example which I provided in error message in pull request which you closed).

But why don't just send me "Internal server error" message? Well obviously that would broke my application because I expect JSON in response. Wait a minute. I expect specific error classes in my try catch block too instead of `TypeError: Cannot read property 'join' of undefined`

Luckily, GitHub has people who actually work for full time and they accept free help. When someone tells them: hey, here is the problem, please fix it! They do. Unlike you, because you have little free-time. Fortunately for all users of this library, I made a pull request with just 1 simple line of code which prevents people from bug. Why don't you click the button 'Merge' if that would make everyones life better?

**Comment by icebob** [comment]
I also accept help, but not partial help and not which good for only some persons. You fix an issue that you faced. But why only fix it in this PR? Why is it not handle other properties in other rules as well?

By the way, fixes are not just one line. Need to cover unit tests as well (in my libraries). _I don't merge PRs without tests._

**Comment by VityaSchel** [comment]
> I also accept help, but not partial help and not which good for only some persons. You fix an issue that you faced. But why only fix it in this PR? Why is it not handle other properties in other rules as well?
> 
> By the way, fixes are not just one line. Need to cover unit tests as well (in my libraries). _I don't merge PRs without tests._

I offer free help, it does the job: fixes this particular issue. If I was collaborator, I would fix all similar issues.

What so you mean by tests? I should write a test which passes when you get this error? If you really think I should write this test, please give me instructions on where is the unit tests must be written. I'll open another PR with commit which adds 1 line to enum.js file and 1 test for this error handler.

**Comment by VityaSchel** [comment]
I opened another pull request with fix + tests

**Comment by VityaSchel** [comment]
Please let me know if you can't merge this PR because of broken code or incorrect code formatting style

**Comment by VityaSchel** [comment]
@icebob I’m afraid I will have to open a duplicate of this issue just to keep it in ‘Open issues’ tab, because you muted this one and will ignore every new message here. If I’m wrong, please reopen this issue and tell me where is my code broken or accept pull request.

**Comment by icebob** [comment]
I've seen the #250, but as you see, the tests failed, so the code is not correct.
