### ISSUE TITLE
type email

### ISSUE THREAD

**Issue by sajcics** [icebob/fastest-validator#257]
WHAT? 
Type email is not checking how many '@' symbols have.

EXAMPLE:
Here is an example how I defined rule for name field.
` email: 'email|max:255|normalize',`

testing with email: 
- `demo@some@some.com`

validation passes as valid.

EXPECTING:
I am expecting validation to fail.

VERSION:
latest: 1.11.1
nodejs: 14

**Comment by intech** [comment]
Set in rule `mode: "precise"` for email field

**Comment by sajcics** [comment]
@intech thanks. it's working.
