### ISSUE TITLE
custom error objects

### ISSUE THREAD

**Issue by higoka** [icebob/fastest-validator#259]
Im creating a rest api and use `fastest-validator` for my form validation. 
For the most part it works fine, however sometimes i need to return some additional error information
which as far as i know is not possible (yet)? Currently we can only change the error message but it would be 
better to allow changing or setting a entire custom error object. 

Something like this:
```js
{
  type: 'stringMin',
  expected: 8,
  actual: 4,
  field: 'password',
  message: "The 'password' field length must be greater than or equal to 8 characters long.",
  
  // custom added properties
  code: 400,
  foo: true,
  bar: 'xyz'
}
```

Is there any plans to implement this? Or any workarounds?

**Comment by erfanium** [comment]
Just create your custom middleware for errors. This is not something that concerns us

**Comment by higoka** [comment]
> Just create your custom middleware for errors. This is not something related to validator itself

can you give a quick example how im not sure how i can implement that in a middleware

**Comment by erfanium** [comment]
> can you give a quick example how im not sure how i can implement that in a middleware

Which framework you are using?

**Comment by higoka** [comment]
> > can you give a quick example how im not sure how i can implement that in a middleware
> 
> Which framework you are using?

express

**Comment by erfanium** [comment]
I'm not a express user, but something like this should work
```js
app.use((req , res, next) => {
   if (req.statusCode !== 400) return next();
   req.body = {...}
   next();
})
```

**Comment by higoka** [comment]
okay i will try to figure it out somehow but thanks for your time and patience!
