### ISSUE TITLE
Bug with type objectID

### ISSUE THREAD

**Issue by mercuryskies** [icebob/fastest-validator#260]
Hi! 
There is a bug when using "objectID" type as it now imported from mongodb as ObjectId. 
And it works only with alias – _import { ObjectId as ObjectID } from 'mongodb'_

To use just _const { ObjectId } = require('mongodb')_ , rule needs to be updated from **ObjectID** to **ObjectId**

**Comment by erfanium** [comment]
`objectID` rule will be removed in next major version (see #252)
So better implement your custom rule for objectId. it's easy
