### ISSUE TITLE
How to validate data based on another property in the data?

### ISSUE THREAD

**Issue by faustbrian** [icebob/fastest-validator#262]
When working with some more complex objects in AJV I'm able to do something like `min: { $data: "1/a/min" }` but can't seem to figure out how to do this with this package.

```js
{
    a: {
        min: 1,
    }
    b: {
        min: "this should use the value of a.min",
    }
}
```

I tried a custom validator but I don't seem to ever have access to the full object inside the `check` function, just the value that is currently being validated.

**Comment by erfanium** [comment]
Just create a const variable, easy and declarative:
```js
const min = 10;

schema = {
    a: {
        min,
    }
    b: {
        min,
    }
}
```

**Comment by faustbrian** [comment]
It isn't a fixed value so this won't work. The way `{ $data: "1/a/min" }` works is that it'll grab the `a.min` value from the object I'm validating.

**Comment by erfanium** [comment]
I know, but I don't see an advantage in using this method. There's no problem to fix
