### ISSUE TITLE
uuid default version

### ISSUE THREAD

**Issue by ngraef** [icebob/fastest-validator#264]
The [docs](https://github.com/icebob/fastest-validator#uuid) say the `uuid` validator's `version` property defaults to `4`. However, a schema without a specified `version` will accept any version. If the intention is to have v4 be the default, then there is a bug in the code. Otherwise, if this is the intended behavior, the docs should be fixed.

```js
const schema = {
    uuid: { type: "uuid" }  // No version specified. Expect v4 default
};
const check = v.compile(schema);

check({ uuid: '9a7b330a-a736-51e5-af7f-feaf819cdc9f' });  // Passes with a v5 uuid
```

**Comment by icebob** [comment]
Thanks, I've fixed the docs, because there is no default value in code.
