### ISSUE TITLE
[QUESTION] Accessing values of other fields from a custom rule

### ISSUE THREAD

**Issue by hugohabicht01** [icebob/fastest-validator#274]
I'm trying to validate nested objects that have dynamic children elements. Depending on what the value of an enum is, I would like to validate another field. Is there any way I could access the passed value of other fields  in a custom checker function?

**Comment by erfanium** [comment]
Even if it is possible, it's not recommended. validation rules must be encapsulated and they should not depend on other fields value. I can help you better if you provide an example of what you want

**Comment by hugohabicht01** [comment]
I'm using a private microservice framework that uses fastest-validator as the validator for incoming data. The data that comes in is in JSON depending on what the value of a enum is, another field will need to be validated differently, kind of like a generic  interface in typescript. e.g.:
```ts
export interface Question<T extends QuestionTypes> {
  questionType: QuestionTypeEnum;
  details: T;
};
export enum QuestionTypeEnum {
  multipleChoice = "multipleChoice",
  linearScale = "linearScale",
};
export interface MultipleChoiceQuestion {
....
}
export interface LinearScaleQuestion {
...
}
```
Examples for the incoming JSON would be:
```json
{
  "questionType": "multipleChoice",
  "details": {
    "foo": "foo"
  }
}
```
or 
```json
{
  "questionType": "linearScale",
  "details": {
    "bar": "bar"
  }
}
```
I hope the examples are understandable, what I'm trying to do is, depending on what the field "questionType" is, another field needs to be validated differently... 
I would be grateful for any suggestions on how to achieve this using fastest-validator.

**Comment by plashenkov** [comment]
> it's not recommended. validation rules must be encapsulated

What it means "not recommended" and "must"? Maybe in simple cases — yes, you don't need this. But in more or less complex cases sometimes you absolutely need this. This is not a programmer's choice, but an objective requirement.

Sometimes the schema of some fields depend on other fields values. For example, you validate a form, where you have different field requirements depending on other field/fields choice. This is a simple and obvious case. But in especially difficult cases these requirements may have complex, branched structure where fields depend on siblings, parents or event grandparents field values.

**Comment by plashenkov** [comment]
Well, sometimes you depend not only on input data, but even on some other existing data.

For a practical example: you have an existing entity data, and you get an input to patch this entity data. You need to validate this input.

For example, the entity data has a field or fields containing an array of some objects. And the new data you have as an input now (to update your entity) can contain objects already presented in the original entity—in this case you just need to update them, so all these objects' fields are optional. If some objects are new, not presented in the original entity, you want to mark all or some fields of such objects as mandatory, and validation must fail if they are not presented.

**Comment by erfanium** [comment]
> Well, sometimes you depend not only on input data, but even on some other existing data.

fastest-validator (and other validators as well) are `schema` validator. not a request validator.
Schemes are stateless, like interfaces. They can't depend on database or time. so schema validators never meet all your needs and you should add extra validation layers if you need.

**Comment by hugohabicht01** [comment]
My question wasn't about causing a big argument, I was just wondering if it is possible to do what I'm trying to do.... Is there any way to achieve this with fastest-validator, or do I have to write another middleware?

**Comment by erfanium** [comment]
@hugohabicht01
I think you can do this by `multi` rule. think like this way:
```ts
interface TypeAQuestion {
  type: "a",
  detail: {
     foo: string
  }
}

interface TypeBQuestion {
  type: "b",
  detail: {
     bar: number
  }
}

type Question = TypeAQuestion | TypeBQuestion

const type_a_schema = {
  type: { type: "equal", value: "a" },
  detail: {
    type: "object",
    props: { foo: "string" }
  }
}

const type_b_schema = {
  type: { type: "equal", value: "b" },
  detail: {
    type: "object",
    props: { bar: "number" }
  }
}

const schema = { type: "multi", values: [type_a_schema, type_b_schema] }
```
