### ISSUE TITLE
Add option to set custom message error in configuration

### ISSUE THREAD

**Issue by guumo** [icebob/fastest-validator#28]
I think it's very important customize error for a individual configuration field, pass the message key. For example:

`first_name: { type: "string", min: 3, max: 25, message: "What is your name?" },`

**Comment by ispyinternet** [comment]
Something I wanted too, I hacked in a solution that works for simple use, not sure what would be required for more complex cases like arrays, or multiple validators. 

````
const schema = {
    id: { type: "number", positive: true, integer: true , messages: { required: "id is a required field" }},
    name: { type: "string", min: 3, max: 255, messages: { stringMin: "Your name is too short" } },
    status: "boolean" // short-hand def
};
 
console.log(v.validate({ name: "J", status: true }, schema));

// output
[ { type: 'required',
    expected: undefined,
    actual: undefined,
    field: 'id',
    message: 'id is a required field' },
  { type: 'stringMin',
    expected: 3,
    actual: 1,
    field: 'name',
    message: 'Your name is too short' } ]
````

My fork is at https://github.com/ispyinternet/fastest-validator

Not a confident contributor so, if the author is up for this functionality perhaps they could implement it more elegantly / robustly?

**Comment by intech** [comment]
Diff: https://github.com/icebob/fastest-validator/compare/master...ispyinternet:master

**Comment by ispyinternet** [comment]
I've updated to the new code and opened a pull request.

**Comment by icebob** [comment]
Released https://github.com/icebob/fastest-validator/releases/tag/v0.6.14
