### ISSUE TITLE
validate false if two field is equal

### ISSUE THREAD

**Issue by shafaprince** [icebob/fastest-validator#280]
How I have a condition to validate ```true``` if two field is not equal (this two field is not numbers):
```javascript
{
    "_id":"619e00c177f6ea2eccffd09f",
    "parent_id": "619e00c177f6ea2eccffd09f",
}
```
I know there is a ```type``` to check if they are [equal](https://github.com/icebob/fastest-validator#equal) but I want to check the opposite:
```javascript
const schema = {
    password: { type: "string", min: 6 },
    confirmPassword: { type: "equal", field: "password" }
}
const check = v.compile(schema);

check({ password: "123456", confirmPassword: "123456" }); // Valid
check({ password: "123456", confirmPassword: "pass1234" }); // Fail
```

**Comment by icebob** [comment]
For this use case, there is not built-in rule. You can do it with custom rule.

**Comment by erfanium** [comment]
@shafaprince Also there's no reason to check both password and confirmPassword fields at backend side. You can only pass password value to the server.

**Comment by shafaprince** [comment]
According to [Meta information for custom validators](https://github.com/icebob/fastest-validator#meta-information-for-custom-validators):

> You can pass any extra meta information for the custom validators which is available via context.meta.

so I can compare any two field that I want. In my to compare ```_id``` and ```parent_id``` I can use this:
```javascript
const v = new Validator({
    useNewCustomCheckerFunction: true,
    messages: {
        notEqual: "دو دسته نمی‌تواند یکی باشد"
    }
});

const editSchema = {
    _id: { type: "string" },
    parent_id: {
        type: "string",
        custom: (value, errors, schema, name, parent, context) =>{
            if (context.data._id === value) errors.push({type: "notEqual"})
            return value
        }
    }
};
```
