### ISSUE TITLE
No standard/default error message for url types

### ISSUE THREAD

**Issue by benjsicam** [icebob/fastest-validator#29]
```javascript
let schema = {
    url: { type: "url" }
}

v.validate({ url: "www.facebook.com" }, schema); // Fails but blank/empty error message is returned
```

Based on the docs and code, there isn't a standard/default error message for url types. https://github.com/icebob/fastest-validator#message-types

**Comment by icebob** [comment]
Thanks. Could you make a PR? Just need to add `url` to [this file.](https://github.com/icebob/fastest-validator/blob/master/lib/messages.js#L42)
