### ISSUE TITLE
Backward compatibility broken when migrating to version `1.12.0`

### ISSUE THREAD

**Issue by FFKL** [icebob/fastest-validator#297]
In versions prior to `1.12.0` all validation errors are returned together, but then the `strict`-related error became a priority.
You can change the `fastest-validator` version in the [example](https://codesandbox.io/s/recursing-monad-2ytp9e?file=/src/index.js) and verify it.

**Comment by icebob** [comment]
The issue came with #272 by @0x0a0d here: https://github.com/icebob/fastest-validator/pull/272/files#diff-7380b3ab547c30fffa792d657dffe20479df9bcebf4932f8a97520611241cd9eR72-R74

@0x0a0d can we remove this condition?

**Comment by 0x0a0d** [comment]
> The issue came with #272 by @0x0a0d here: https://github.com/icebob/fastest-validator/pull/272/files#diff-7380b3ab547c30fffa792d657dffe20479df9bcebf4932f8a97520611241cd9eR72-R74
> 
> @0x0a0d can we remove this condition?

This condition cannot be completely removed as it is required for `multi rule`, unless in the `multi rule`, before call checker, the data must be `deepClone`, otherwise object `strict remove` will change it and next validation will be failed
