### ISSUE TITLE
Multi-schema nullable validators not working as expected.

### ISSUE THREAD

**Issue by ccampanale** [icebob/fastest-validator#303]
I'm using `fastest-validator@1.13.0` and attempting a multi-validator schema to represent the union type `string | boolean | null` while disallowing `undefined` but this is not working as I expect.

According to the docs:
> If you want disallow `undefined` value but allow `null` value, use `nullable` instead of `optional`.

```js
const schema = {
    dateString: [
        { type: "string", nullable: true },
        { type: "boolean", nullable: true }
    ]
}

check = v.compile(schema);

check({ dateString: true }); // Valid
check({ dateString: new Date().toISOString() }); // Valid
check({ dateString: null }); // Fail
```

The third test should pass since both schemas are `nullable`. Instead I see the follow results from the validator:

```js
[
  {
    type: 'required',
    message: "The 'dateString' field is required.",
    field: 'dateString',
    actual: null
  }
]
```

Let me know if I a missing something and thanks for taking a look!

**Comment by icebob** [comment]
The `nullable` is not working with `multi` rule shorthand format, try this form:

```js
const schema = {
	dateString: {
		type: "multi", rules: [
			{ type: "string" },
			{ type: "boolean" }
		], nullable: true
	}
};
```
![image](https://user-images.githubusercontent.com/306521/187038686-d97bb254-524d-4ecb-8837-78a8d17b6c6e.png)

**Comment by ccampanale** [comment]
@icebob Thanks for addressing this. The long form `multi` - which I honestly must have glossed over in the docs - works great.

**Comment by icebob** [comment]
Nop, by the way, the issue fixed in the latest version, so your original code can work as well.
