### ISSUE TITLE
Performance issues: compile function

### ISSUE THREAD

**Issue by ipetrovic11** [icebob/fastest-validator#310]
Using the fastest validator in a loop(for/while/etc...), for example, when an array of elements is checked will have a bad impact on performance. It works great if you do check for the whole array at once, but if you want to do one-by-one, which could be the case if you want to process the array partially, will have a bad impact on performance.

The core of the issue is "compile" function since for every element it will compile schema into a dynamic function.

An idea for a solution is to allow "compile" to happen only once and call only "check", multiple times. This interface would need to be exposed outside.

**Comment by erfanium** [comment]
Please share your use case code that shows this performance issue

**Comment by ipetrovic11** [comment]
Looks like we were not using v.compile but v.validate which was the issue.
