### ISSUE TITLE
Single and list of data auto-handling

### ISSUE THREAD

**Issue by DenisFerrero** [icebob/fastest-validator#313]
Hi, in my projects I handle many params as an array and they can be passed as a single value or as a list of values, but every time I have to manage this case manually

For example:
```js
const Validator = require("fastest-validator");

const schema = {
    name: { type: 'multi', rules: [{ type: 'string' }, { type: 'array', items: 'string' }] }
};

const check = (new Validator()).compile(schema);

const params = { name: 'John' }

check(params);
if (params.name && !Array.isArray(params.name)) params.name = [params.name];

const query = `SELECT * FROM users WHERE name IN (${params.name.join(', ')})`
```

It would be great if this array conversion could be done directly by the validator using a parameter. For example:

```js
const Validator = require("fastest-validator");

// By running an array validation with the wrap: true property the param even if it's a string it's wrapped inside an array before running the validation
const schema = {
    name: { type: 'array', items: 'string', wrap: true }
};

const check = (new Validator()).compile(schema);

const params = { name: 'John' }

check(params);
// params.name now is equal to ['John']

const query = `SELECT * FROM users WHERE name IN (${params.name.map(name => `'${name}'`).join(', ')})`
```

**Comment by erfanium** [comment]
I think that's out of scope, even TypeScript doesn't have support for this

**Comment by erfanium** [comment]
I know it's useful but it can't be done at validation layer. it has some technical issues. e.g. how should we handle nested arrays? this logic only works for simple arrays like `string[]` and not for something like `string[][]`

**Comment by DenisFerrero** [comment]
Ok, that's right some cases can't be covered. Is there a way to add this property wrap: true with the related behavior into the validator using plugins? Even if it's out of scope it will be really useful at least to have it in my projects. There are aliases but I prefer to don't use them as the schemas are used by an external package to compile the Swagger automatically before the compilation.
Otherwise, I can also do this but it limits the usage of the custom methods of the validator in case of an array
```js
function wrapFn (value) {
   if (value && !Array.isArray(value)) value = [value];
   return value;
}

const schema1 = {
   users: { type: 'array', items: 'string', custom: wrapFn }
}
const schema2 = {
   auths: { type: 'array', items: 'number', custom: wrapFn }
}
```

**Comment by icebob** [comment]
The `convert` option does the same for primitive types to convert string to number or date. Maybe we can do it for arrays, so if the input is not an array, it wraps the input into an array.

**Comment by DenisFerrero** [comment]
That would be great, so in the case of string[][] it's not considered an improper validation as it's just a data conversion process

**Comment by icebob** [comment]
Yeah, it just a helper to make an array wrapping. Could you create a PR?

**Comment by DenisFerrero** [comment]
Closing issue as the changes have been merged
