### ISSUE TITLE
haltOnFirstError is missing from the type definitions

### ISSUE THREAD

**Issue by HeyJ0e** [icebob/fastest-validator#316]
The option `haltOnFirstError` is missing from the definition of the `Validator` constructor.

It should be added to the [ValidatorConstructorOptions](https://github.com/icebob/fastest-validator/blob/master/index.d.ts#L898).

![err](https://user-images.githubusercontent.com/24508123/219651519-49e10709-fe2b-4190-bcbf-924f4cfcda52.jpg)

**Comment by icebob** [comment]
Could you create a fix PR, please?
