### ISSUE TITLE
Error: Cannot find module 'prettier'

### ISSUE THREAD

**Issue by muturgan** [icebob/fastest-validator#325]
code for reproducing:
```js
const Validator = require("fastest-validator");
const v = new Validator({debug: true}); // debug mode is an error trigger
const checkFunc = v.compile({name: { type: "string"}});
```
it leads to error:
```
Error: Cannot find module 'prettier'
Require stack:
- path-to-project/node_modules/fastest-validator/lib/helpers/prettier.js
- path-to-project/node_modules/fastest-validator/lib/validator.js
- path-to-project/node_modules/fastest-validator/index.js
- path-to-project/my-file.cjs
```
my setup:
ubuntu 22.04
node 14.21.3
fastest-validator 1.17.0

**Comment by intech** [comment]
@muturgan do you install packages with development dependencies or only a production flag?

**Comment by muturgan** [comment]
@intech my project has only one dependency - fastest-validator.
it was installed via following comand: `npm i fastest-validator`
and i dont have a prettier in my dev dependencies.
even if have. there may be a case with `--only=prod` installation. in a docker container building for example.

**Comment by muturgan** [comment]
@intech here's a demo of the bug playback
https://github.com/icebob/fastest-validator/assets/34779116/d3a5109e-f598-4e7a-ae5a-9647b14436a8

**Comment by icebob** [comment]
`prettier` is a devDependency and no need for normal usages. The `debug: true` option is a development setting and it needs prettier. So remove the debug settings, or if you need it, install the prettier manually.

**Comment by muturgan** [comment]
@icebob It would be nice to point this in a documentation or d.ts file. An interface just show me that i can use this option without any restriction

**Comment by icebob** [comment]
So the problem is in the d.ts file, because this `debug` option is not published, the documentation doesn't mention it.
