### ISSUE TITLE
Nullable not working inside Array items

### ISSUE THREAD

**Issue by lucas-subli** [icebob/fastest-validator#331]
I have a situation where items in an array can be either a number or null if the data is not available.
However passing `nullable: true` to array itens does not seem to allow for that.

```
const Validator = require("fastest-validator");

const v = new Validator();

const schema = {
  slices: {
    type: 'array',
    length: 3,
    items: {
      type: 'number',
      min: 0,
      max: 99,
      nullable: true,
    },
  },
};

check = v.compile(schema);

console.log('Numbers = ', check({ slices: [1, 2, 3] })); // Works
console.log('With null = ', check({ slices: [1, 2, null] })); // Fails
```

![image](https://github.com/icebob/fastest-validator/assets/11154048/42b67aa8-42f9-4a1f-841c-70324e6238f0)

**Comment by FerX** [comment]
I have tested your code and it does not give me any problems. 
Please check that you are using the latest version.

![image](https://github.com/icebob/fastest-validator/assets/4459841/5af63016-cc9d-438f-b724-940182db39c5)

**Comment by lucas-subli** [comment]
I can confirm that in 1.17.0, it does work as expected.
Sorry for not double-checking the version.
Closing.
