### ISSUE TITLE
allow to add metas in the schema

### ISSUE THREAD

**Issue by thib3113** [icebob/fastest-validator#338]
Is it possible to add some metas in the schemas / rules ? 

like : 
```js
    dot: {
        $$metas: {
          openapiName: 'dot'
        },
        $$type: "object",
        x: "number", // object props here
        y: "number", // object props here
    }
```

I think it can be usefull to reuse the validation params to do others things ( like here, generating openapi from params ) . 

The keys starting with $$ can be just skipped from the validation, categorized as "system properties" ? (this can also allow to add other systems properties without breaking changes)

**Comment by icebob** [comment]
Good idea, could you create a PR?

**Comment by thib3113** [comment]
@icebob what did you think about something like that : https://github.com/thib3113/fastest-validator/commit/d37a2dc81a5f7f5c56274ac3dcaf7ce99bceae10 ? 

My idea is to remove all keys starting with `$$` . To mark them as "reserved" ( for you in the future, or other plugins and things like that ? )

so, we can do something like : 
```js
const schema = {
  $$description: "user",
  id: { $$description: "user Id", type: "number", positive: true, integer: true },
  address: { 
    $$description: "delivery address"
    type: "object", 
    props: {
      street: { type: "string" },
      city: { type: "string" },
      zip: { type: "string", length: 5 }
    }
  }
}
```

**Comment by icebob** [comment]
It can be good but it's not as easy as you think :)
If you search for "$$" in the code you will see that the validator uses `$$root`, `$$async`, `$$type` and `$$strict` in different places. So you can't remove them, only others.

**Comment by thib3113** [comment]
@icebob . yes, I know . 

I tryed to run the tests with this, and no tests crash (so maybe, there is something not tested) .

Else, 
 - `$$async` seems to be used only in `compile` (so before `getRuleFromSchema`) / same for `$$root` / seems the same for $$strict
 - `$$type` seems to be used in `resolveType` (in `getRuleFromSchema`) only, and only on current schema ( it will call `getRuleFromSchema` only on sub rules ), and so I removed the $$ after

**Comment by icebob** [comment]
Could you create a PR?
