### ISSUE TITLE
min and max doesnt give desired result for type number

### ISSUE THREAD

**Issue by mhdaslam790** [icebob/fastest-validator#340]
hey there
i am trying to set min length of a variable to 10 but the result i am getting is below
` phoneNumber: { type: 'number', positive: true, integer: true, min: 10, optional: false },` my validator and when i pass number in phoneNumber = 12345678 it does gives true but when i pass any number below 10 (i.e=> 1,3,5 etc) it returns falls  .
 can i know how min and max works?

**Comment by fernandodevelon** [comment]
If you take it as a number, it is intended >=10, for your use I recommend using the string type with min and numeric property
