### ISSUE TITLE
Auto Schema Generation from TypeScript Interface or Type ?

### ISSUE THREAD

**Issue by imyounas** [icebob/fastest-validator#343]
Hi - Is it possible to automatically generate schema from TS Interface or Type ? Or is there any future plans for it ?

**Comment by fernandodevelon** [comment]
I believe it would be possible, but I don’t think it’s in the project’s roadmap. Moreover, while TypeScript defines the type, validation may require many additional rules.

**Comment by FerX** [comment]
I believe it would be possible, but I don’t think it’s in the project’s roadmap. Moreover, while TypeScript defines the type, validation may require many additional rules.

**Comment by icebob** [comment]
It's not a planned feature, for this purpose you can use other validator libraries, like valibot or zod.
