### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by lfades** [icebob/fastest-validator#42]
This library is great, I love it!, the only thing I'm really missing is Typescript types, if they can be in the repo, like in [ajv](https://github.com/epoberezkin/ajv/blob/master/lib/ajv.d.ts), even better.

I may be able to work on this in the future if this ends up being my validator of choice.

**Comment by icebob** [comment]
Thanks. It would be great if you can help with Typescript.

**Comment by andersnm** [comment]
Possible starting point based on the pseudo BNF in #31:
https://gist.github.com/andersnm/0092addbf5ecb203ff9063bb46e3e27f

Note the comments about the `SchemaType`

Although it would be nice to port the project to TypeScript and not having to maintain the .d.ts

**Comment by sittingbool** [comment]
Got you a pull request for it. Let me know if there are any issues with it. I tested it in my project where i started writing my own definitions file for your project. I now tested with all the examples from your README.md and typescript transpiler always finished without errors.
