### ISSUE TITLE
[Enhancement] Validating uuids

### ISSUE THREAD

**Issue by kristijanhusak** [icebob/fastest-validator#43]
Hey,

do you plan to add support for validating uuids?

**Comment by intech** [comment]
@kristijanhusak fix, see https://github.com/icebob/fastest-validator/pull/55

**Comment by icebob** [comment]
Released: https://github.com/icebob/fastest-validator/releases/tag/v0.6.14

**Comment by cinghingolo** [comment]
Hey there, I see that uuid type validation and tests were added in the code, but the uuid type is not active yet in `v0.6.14`..
Can you please add the uuid type in the `lib/validator.js` file?

**Comment by intech** [comment]
> @icebob Hey there, I see that uuid type validation and tests were added in the code, but the uuid type is not active yet in `v0.6.14`..
> Can you please add the uuid type in the `lib/validator.js` file?

this is my error :confused:

**Comment by icebob** [comment]
Released the fix in 0.6.15

**Comment by cinghingolo** [comment]
@intech @icebob thanks a lot :)
