### ISSUE TITLE
Custom validator function access to the object

### ISSUE THREAD

**Issue by icebob** [icebob/fastest-validator#5]
```js
const schema = {
	email: { 
		type: "custom", 
		check(value, schema, obj) {
			return obj.username || obj.email ? null : this.makeError(...);
		}
	}
};
```

**Comment by chameleonbr** [comment]
This already works?

**Comment by icebob** [comment]
Not yet.

**Comment by tinchoz49** [comment]
Hi @icebob ! I want to help with this feature.

Currently, the check function is receiving `value`, `schema` and `stack`. How would you prefer to change the check function to receive the obj values?

1. If we don't want to do a breaking change we can send the `obj` has a fourth value but I feel that when we are sending to many parameters something is not right.
2. We can do a refactor to receive `(value, schema, { stack, obj })`
3. Or we can do something like the ctx object in the handlers action of moleculer. Of course, this would be a breaking change.

```javascript
const schema = {
	email: { 
		type: "custom", 
		check({ value, schema, obj }) {
			return obj.username || obj.email ? null : this.makeError(...);
		}
	}
};
```

**Comment by icebob** [comment]
Great @tinchoz49! Thanks.

First of all, I plan I will rewrite the whole lib to be faster (in some months), so now would be good to choose a non-breaking-change and easy solution. 

The `stack` is not used in custom validator func, but it is used to validate nested objects. So the signature of `check` in custom validator must be same as the compiled object validator at [https://github.com/icebob/fastest-validator/blob/master/lib/validator.js#L157](here). In this case, now I prefer the first solution. Add a 4th parameter to both function.

The lib is covered 100% tests, so you can check the results. If you need help, just write me.

**Comment by tinchoz49** [comment]
> First of all, I plan I will rewrite the whole lib to be faster (in some months), so now would be good to choose a non-breaking-change and easy solution.

Faster than already it's :open_mouth: ? that's great :smile: 

is it going to change how we define the schemas or is more like an internal rewrite?

**Comment by icebob** [comment]
It's just an internal rewrite. The schema won't be touched. It will generate the `check` code from templates and compile with `new Function()`

And would be good to add some sanitization features too (trim, convert to int, convert to boolean, convert to string...etc)

**Comment by icebob** [comment]
#17

**Comment by tinchoz49** [comment]
> And would be good to add some sanitization features too (trim, convert to int, convert to boolean, convert to string...etc)

Yes, that would be a cool featurea

**Comment by icebob** [comment]
Not sure, because it seems `ajv` is faster :disappointed: : https://github.com/icebob/validator-benchmark
This is the reason why I want to rewrite it :)

**Comment by icebob** [comment]
Published in v0.6.6

**Comment by chameleonbr** [comment]
The ajv generate JS code and compile it using dot.js(https://www.npmjs.com/package/dot).

**Comment by icebob** [comment]
Yes, I want to implement a similar solution, but with sanitizations.
