### ISSUE TITLE
Email rule allows undefined

### ISSUE THREAD

**Issue by lukeed** [icebob/fastest-validator#54]
Passing `undefined` to a compiled schema with `type: 'email'` will not return an error.

Since there isn't an accompanying `empty` option, I would expect `email` to require a value. I would also be happy with an `empty` option so that the rule behaves closer to `string`.

---

I can open a separate issue, but the same applies to the built-in `url` rule.

Thanks!

**Comment by icebob** [comment]
I've checked but it's working for me.

```js
let Validator = require("../index");

let v = new Validator();

const schema = {
	email: { type: "email" },
};

const check = v.compile(schema);

console.log(check({ email: "john@gmail.com" }));

console.log(check({ email: undefined }));
```

**Output**
```
true
[ { type: 'required',
    expected: undefined,
    actual: undefined,
    field: 'email',
    message: 'The \'email\' field is required!' } ]
```

**Comment by lukeed** [comment]
Totally my fault, forgot to update 😃 

Thank you~!
