### ISSUE TITLE
Typedefs are broken

### ISSUE THREAD

**Issue by anri-asaturov** [icebob/fastest-validator#64]
Typedefs are so broken, guys, please consider disabling them until sensible PR is made.

some examples: 
- missing 'empty'
- 'items' can be an object

I'm sure I will find more if i continue looking at api.

**Comment by akazakou** [comment]
Also not working multiple validators for `validator.compile` method

**Comment by couellet** [comment]
Definition file looks good in the repo though, but somehow npm package is out of sync :/

**Comment by icebob** [comment]
Published in v0.6.16

**Comment by couellet** [comment]
My bad, the defs file wasn't correct after all. I just submit a pull request fixing it.

**Comment by v1tail** [comment]
https://github.com/icebob/fastest-validator/blob/master/index.d.ts doesn't work with the new release (0.6.16). TypeScript signals an error "An export assignment cannot be used in a module with other exported elements."

**Comment by akazakou** [comment]
@v1tail Yes. My bad. I fixed it in icebob/fastest-validator#68 PR but it still opened
