### ISSUE TITLE
Multiple validators - All conditions to true

### ISSUE THREAD

**Issue by soubhikchatterjee** [icebob/fastest-validator#69]
Hello

I am using fastest-validator in one of my major nodejs project and I was wondering if its possible to make the "Multiple validators" return true only if ALL the conditions are true. Currently it checks if any one condition is true and returns true if so.

Thanks for the wonderful library.

T&R
Soubhik

**Comment by icebob** [comment]
Hi @soubhikchatterjee,
it is not available because this feature is planned to handle multiple value types for properties.

**Comment by soubhikchatterjee** [comment]
Thats so sad. I finally had to switch to Indicative Validator (https://indicative.adonisjs.com/guides/master/introduction)

Thanks anyways
