### ISSUE TITLE
Require full object or nothing

### ISSUE THREAD

**Issue by kozikkam** [icebob/fastest-validator#72]
Hey,
I have a validation as follows:
```
      location: { type: 'object', optional: true, props: {
        longitude: { type: 'number' },
        latitude: { type: 'number' },
      } },
```

It should pass in two cases:
1. `{ location: { longitude: someNumber, latitude: someNumber } }`
2. `{ }`

Right now for second case it will throw error, thinking `location.longitute` and `location.latitude` are required.

**Comment by TriStarGod** [comment]
Is it possible for fastest-validator not to validate undefined properties or at least provide an option for it? Also, is there an option for fastest-validator to return the first error it found without proceeding further?

**Comment by icebob** [comment]
It is not possible.
