### ISSUE TITLE
Type: boolean, equal: true not working

### ISSUE THREAD

**Issue by murat-mehmet** [icebob/fastest-validator#77]
I need to validate if an boolean field is true:

```
const schema: ValidationSchema = {
    agree: {type: "boolean", equal: true}
}
const obj = {
   agree: false
}

v.validate(obj, schema)
```

result -> true

Am I doing something wrong?

EDIT: seems like there is no 'equal' or 'nonEqual' check in boolean rule

**Comment by icebob** [comment]
https://github.com/icebob/fastest-validator/pull/94
