### ISSUE TITLE
Feature: Add display name for fields

### ISSUE THREAD

**Issue by murat-mehmet** [icebob/fastest-validator#78]
Currently this is the message shown:
`The 'firstName' field length must be greater than or equal to 4 characters long!`

We could define a display field to be printed in the message field so it looks better
```
{
    firstName: {type: "string", min: 4, max: 16, display: 'First Name'},
}
```
`The 'First Name' field length must be greater than or equal to 4 characters long!`

Are you ok with the concept? I could send a PR if you dont mind.

**Comment by icebob** [comment]
Good idea, please create a PR but please use `displayName` instead of `display`.

**Comment by murat-mehmet** [comment]
Please check the PR and tell me if anything needs an update. I tested the code and everything seems to work.

**Comment by xgenvn** [comment]
I'm against this, either you use the display as a key (think i18n) or we provide some custom events for extending UI related functionalities. I don't think it's a good idea to make a general validator with some UI logic.
Something like
```
v.on("fieldError", function(field, schema, objectValue){
...
});
```
