### ISSUE TITLE
optional field - prevent null or undefined

### ISSUE THREAD

**Issue by atlanteh** [icebob/fastest-validator#80]
Can we have a prop on the fields that tells the validator to treat null or undefined as values that need to be tested?

I want a string field to optional, but if it's specified, it must be a string and cannot be null or undefined. I was thinking of maybe using a custom validator, but it seems my validator never gets called if the input is null.

**Comment by icebob** [comment]
`optional: true` ?

**Comment by atlanteh** [comment]
If I set optional and the field is null or undefined the validation passes. I need it to fail

**Comment by cs4inctec** [comment]
@atlanteh you could use a custom validator: https://github.com/icebob/fastest-validator#custom-validator

**Comment by atlanteh** [comment]
I can't use a custom validator for that. I see in the code that if the field is optional it returns true for undefined even before calling the custom validator. Is there something that I'm missing. I tried getting it to work with custom validator but couldn't
