### ISSUE TITLE
Add confirm password validator

### ISSUE THREAD

**Issue by zoheirkhonyagar** [icebob/fastest-validator#82]
something just like this : 
```js
var v = new FastestValidator();
let schema = {
    password: { type: "password", confirmed: true }, // required
}

v.validate({ password: "123456", confirm-password: "123456" }, schema); // Valid
v.validate({ password: "123456", confirm-password: "1234567" }, schema); // Fail
v.validate({ password: "123456" }, schema); // Fail
```

**Comment by xgenvn** [comment]
I don't think this should be a basic built-in validator since this is mostly the higher logic than others. Either we support something like "equalTo" which will be more extendable for many use cases. Or using events/hooks like `post validate` to not having some performance penalties in all cases.  For this case, the example of a CustomValidator instead is preferable.

**Comment by kelp404** [comment]
I have the same problem.
I share the back validations to the frontend app.
I can't use custom field to do that. Because I can't get the value of other fields in the check function.

```js
const {validator} = require('../../../core/validations');
const UserSchema = require('../../../../backend/forms/shared/user-schema');

module.exports = validator.compile({
  newPassword: {
    ...UserSchema.password,
    isNeedLowerCase: false,
    isNeedUpperCase: false,
    isNeedNumber: false,
  },
  confirmPassword: {
    type: 'custom',
    check: function (value, schema) {
      // I can't get the value of `newPassword` at here.
      return true;
    }
  }
});
```

**Comment by zoheirkhonyagar** [comment]
> I don't think this should be a basic built-in validator since this is mostly the higher logic than others. Either we support something like "equalTo" which will be more extendable for many use cases. Or using events/hooks like `post validate` to not having some performance penalties in all cases. For this case, the example of a CustomValidator instead is preferable.

I try CustomValidator but I couldn't get the right response that I want.

**Comment by xgenvn** [comment]
@zoheirkhonyagar @kelp404 
Please see my full example here:
https://codesandbox.io/s/vue-template-m2wgu

The idea is you make a custom validator for confirm password fields as an object.
