### ISSUE TITLE
Optional if another field has been filled

### ISSUE THREAD

**Issue by jonathanrc** [icebob/fastest-validator#84]
Is it possible to set optional or not according to the completion of another schema field? I just need to say whether the field is required or not depending on the other, not to perform a custom validation. Example:

```
const schema = {
	type: { type: "enum", values: ['A', 'B'] },
	field_a: {
		type: "string",
		min: 3,
		optional(schema) {
			return (schema.type !== 'A');
		}
	}
};
```

**Comment by jonathanrc** [comment]
Something like the requiredIf of Vuelidate:

`field: { required: requiredIf((model) => { return model.type !== 'A' }) }`

**Comment by xgenvn** [comment]
@jonathanrc see my answer in another issue:
https://github.com/icebob/fastest-validator/issues/82#issuecomment-529847645
