### ISSUE TITLE
remove additional params from object in sanitizaters

### ISSUE THREAD

**Issue by erfanium** [icebob/fastest-validator#99]
I'm using fastest-validator from Moleculer built-in validator.
the output of the validator may have extra additional params.
see this example:
```js
module.exports = {
   name: "myService",
   actions: {
      myAction: {
         name: 'myAction',
         params: {
            name: 'string',
            value: 'number'
         },
         handler(ctx){
            return saveToDb(ctx.params);
         }
      }
   }
};
```
**this code is not safe** because ctx.params may have extra params. I know there are solutions like ramda.pick or lodash.pick ... , but it's very cool if the validator does it.

something like this:

```js
module.exports = {
   name: "myService",
   actions: {
      myAction: {
         name: 'myAction',
         params: {
            name: 'string',
            value: 'number'
         },
         paramsPick: true,  // flag to enable this feature
         handler(ctx){
            return saveToDb(ctx.params);
         }
      }
   }
};


```
or using this different flag: 

```js
module.exports = {
   name: "myService",
   actions: {
      myAction: {
         name: 'myAction',
         params: {
            _pick: true,
            name: 'string',
            value: 'number'
         },         
         handler(ctx){
            return saveToDb(ctx.params);
         }
      }
   }
};
```

**Comment by icebob** [comment]
The new 1.0.0 version will do that: https://github.com/icebob/fastest-validator/blob/master/CHANGELOG.md#sanitizations

**Comment by erfanium** [comment]
@icebob thanks!
how can I use it with moleculer?

**Comment by icebob** [comment]
In the last moleculer 0.14, it is updated to 1.0.0 beta.
In 0.13 here is a sample code: https://repl.it/@icebob/moleculer-validator-100
